FROM golang:1.26-alpine

RUN apk add --no-cache git make curl openjdk17 build-base openssl-dev pkgconf

RUN curl -o allure.tar.gz -Ls https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz && \
    tar -zxvf allure.tar.gz -C /opt/ && \
    ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure && \
    rm allure.tar.gz

RUN go install github.com/jstemmer/go-junit-report/v2@v2.1.0 && \
    go install github.com/axw/gocov/gocov@v1.1.0 && \
    go install github.com/wadey/gocovmerge@v0.0.0-20160331181800-b5bfa59ec0ad

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ENV CGO_ENABLED=1
ENV GOOS=linux

CMD ["go", "test", "-v", "./..."]