sonar.projectKey=Neratus_geoguide
sonar.organization=neratus

sonar.projectName=geoguide
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=\
  **/vendor/**,\
  **/*.pb.go,\
  **/*_mock.go,\
  **/mocks/**,\
  **/testdata/**,\
  **/internal/repository/postgres/sqlc/**,\
  **/internal/domain/interfaces/**,\
  coverage.out,\
  coverage.html,\
  coverage-dashboard.html

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
  **/*_test.go,\
  **/cmd/**,\
  **/migrations/**,\
  **/internal/repository/postgres/sqlc/**

sonar.language=go

sonar.sourceEncoding=UTF-8