// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM "City"
WHERE "id" = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCity, id)
	return err
}

const deleteDistrict = `-- name: DeleteDistrict :exec
DELETE FROM "CityDistrict"
WHERE "id" = $1
`

func (q *Queries) DeleteDistrict(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDistrict, id)
	return err
}

const deleteTransportNode = `-- name: DeleteTransportNode :exec
DELETE FROM "TransportNode"
WHERE "id" = $1
`

func (q *Queries) DeleteTransportNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransportNode, id)
	return err
}

const findCitiesByCountry = `-- name: FindCitiesByCountry :many
SELECT  "id", "name", "population", "is_capital", "coordinates",
       "description", "timezone", "travel_tips", "country_id", "image_id"
FROM "City"
WHERE "country_id" = $1
`

func (q *Queries) FindCitiesByCountry(ctx context.Context, countryID pgtype.UUID) ([]City, error) {
	rows, err := q.db.Query(ctx, findCitiesByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Population,
			&i.IsCapital,
			&i.Coordinates,
			&i.Description,
			&i.Timezone,
			&i.TravelTips,
			&i.CountryID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCityByID = `-- name: FindCityByID :one
SELECT "id", "name", "population", "is_capital", "coordinates",
       "description", "timezone", "travel_tips", "country_id", "image_id"
FROM "City"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindCityByID(ctx context.Context, id pgtype.UUID) (City, error) {
	row := q.db.QueryRow(ctx, findCityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Population,
		&i.IsCapital,
		&i.Coordinates,
		&i.Description,
		&i.Timezone,
		&i.TravelTips,
		&i.CountryID,
		&i.ImageID,
	)
	return i, err
}

const findCityByName = `-- name: FindCityByName :one
SELECT  "id", "name", "population", "is_capital", "coordinates",
       "description", "timezone", "travel_tips", "country_id", "image_id"
FROM "City"
WHERE "name" = $1
LIMIT 1
`

func (q *Queries) FindCityByName(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRow(ctx, findCityByName, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Population,
		&i.IsCapital,
		&i.Coordinates,
		&i.Description,
		&i.Timezone,
		&i.TravelTips,
		&i.CountryID,
		&i.ImageID,
	)
	return i, err
}

const findDistrictsByCity = `-- name: FindDistrictsByCity :many
SELECT "id", "name", "description", "coordinates",
    "city_id", "image_id"
FROM "CityDistrict"
WHERE "city_id" = $1
`

func (q *Queries) FindDistrictsByCity(ctx context.Context, cityID pgtype.UUID) ([]CityDistrict, error) {
	rows, err := q.db.Query(ctx, findDistrictsByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityDistrict
	for rows.Next() {
		var i CityDistrict
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Coordinates,
			&i.CityID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTransportNodeByID = `-- name: FindTransportNodeByID :one
SELECT "id", "name", "type",
    "coordinates", "address",
    "city_id", "image_id"
FROM "TransportNode"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindTransportNodeByID(ctx context.Context, id pgtype.UUID) (TransportNode, error) {
	row := q.db.QueryRow(ctx, findTransportNodeByID, id)
	var i TransportNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Coordinates,
		&i.Address,
		&i.CityID,
		&i.ImageID,
	)
	return i, err
}

const findTransportNodesByCity = `-- name: FindTransportNodesByCity :many
SELECT "id", "name", "type",
    "coordinates", "address",
    "city_id", "image_id"
FROM "TransportNode"
WHERE "city_id" = $1
`

func (q *Queries) FindTransportNodesByCity(ctx context.Context, cityID pgtype.UUID) ([]TransportNode, error) {
	rows, err := q.db.Query(ctx, findTransportNodesByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransportNode
	for rows.Next() {
		var i TransportNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Coordinates,
			&i.Address,
			&i.CityID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCity = `-- name: SaveCity :one
INSERT INTO "City" (
    "name",
    "population",
    "is_capital",
    "coordinates",
    "description",
    "timezone",
    "travel_tips",
    "country_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, 
$5, $6, 
$7, $8, $9)
RETURNING "id"
`

type SaveCityParams struct {
	Name        string       `json:"name"`
	Population  pgtype.Int8  `json:"population"`
	IsCapital   pgtype.Bool  `json:"is_capital"`
	Coordinates pgtype.Point `json:"coordinates"`
	Description pgtype.Text  `json:"description"`
	Timezone    pgtype.Text  `json:"timezone"`
	TravelTips  pgtype.Text  `json:"travel_tips"`
	CountryID   pgtype.UUID  `json:"country_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) SaveCity(ctx context.Context, arg SaveCityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveCity,
		arg.Name,
		arg.Population,
		arg.IsCapital,
		arg.Coordinates,
		arg.Description,
		arg.Timezone,
		arg.TravelTips,
		arg.CountryID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const saveDistrict = `-- name: SaveDistrict :one
INSERT INTO "CityDistrict" (
    "name",
    "coordinates",
    "description",
    "city_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, $5)
RETURNING "id"
`

type SaveDistrictParams struct {
	Name        string       `json:"name"`
	Coordinates pgtype.Point `json:"coordinates"`
	Description pgtype.Text  `json:"description"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) SaveDistrict(ctx context.Context, arg SaveDistrictParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveDistrict,
		arg.Name,
		arg.Coordinates,
		arg.Description,
		arg.CityID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const saveTransportNode = `-- name: SaveTransportNode :one
INSERT INTO "TransportNode" (
    "name",
    "type",
    "coordinates",
    "address",
    "city_id",
    "image_id"
) VALUES
($1, $2, $3, $4, $5, $6)
RETURNING "id"
`

type SaveTransportNodeParams struct {
	Name        string       `json:"name"`
	Type        string       `json:"type"`
	Coordinates pgtype.Point `json:"coordinates"`
	Address     pgtype.Text  `json:"address"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) SaveTransportNode(ctx context.Context, arg SaveTransportNodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveTransportNode,
		arg.Name,
		arg.Type,
		arg.Coordinates,
		arg.Address,
		arg.CityID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const searchCities = `-- name: SearchCities :many
SELECT "id", "name", "population", "is_capital", "coordinates",
       "description", "timezone", "travel_tips", "country_id", "image_id"
FROM "City"
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%')
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchCitiesParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchCities(ctx context.Context, arg SearchCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, searchCities, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Population,
			&i.IsCapital,
			&i.Coordinates,
			&i.Description,
			&i.Timezone,
			&i.TravelTips,
			&i.CountryID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :exec
UPDATE "City"
SET 
    "name" = $2,
    "population" = $3,
    "is_capital" = $4,
    "coordinates" = $5,
    "description" = $6,
    "timezone" = $7,
    "travel_tips" = $8,
    "country_id" = $9,
    "image_id" = $10
WHERE "id" = $1
`

type UpdateCityParams struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Population  pgtype.Int8  `json:"population"`
	IsCapital   pgtype.Bool  `json:"is_capital"`
	Coordinates pgtype.Point `json:"coordinates"`
	Description pgtype.Text  `json:"description"`
	Timezone    pgtype.Text  `json:"timezone"`
	TravelTips  pgtype.Text  `json:"travel_tips"`
	CountryID   pgtype.UUID  `json:"country_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) error {
	_, err := q.db.Exec(ctx, updateCity,
		arg.ID,
		arg.Name,
		arg.Population,
		arg.IsCapital,
		arg.Coordinates,
		arg.Description,
		arg.Timezone,
		arg.TravelTips,
		arg.CountryID,
		arg.ImageID,
	)
	return err
}

const updateDistrict = `-- name: UpdateDistrict :exec
UPDATE "CityDistrict"
SET 
    "name" = $2,
    "coordinates" = $3,
    "description" = $4,
    "city_id" = $5,
    "image_id" = $6
WHERE "id" = $1
`

type UpdateDistrictParams struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Coordinates pgtype.Point `json:"coordinates"`
	Description pgtype.Text  `json:"description"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) error {
	_, err := q.db.Exec(ctx, updateDistrict,
		arg.ID,
		arg.Name,
		arg.Coordinates,
		arg.Description,
		arg.CityID,
		arg.ImageID,
	)
	return err
}

const updateTransportNode = `-- name: UpdateTransportNode :exec
UPDATE "TransportNode"
SET 
    "name" = $2,
    "type" = $3,
    "coordinates" = $4,
    "address" = $5,
    "city_id" = $6,
    "image_id" = $7
WHERE "id" = $1
`

type UpdateTransportNodeParams struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Type        string       `json:"type"`
	Coordinates pgtype.Point `json:"coordinates"`
	Address     pgtype.Text  `json:"address"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

func (q *Queries) UpdateTransportNode(ctx context.Context, arg UpdateTransportNodeParams) error {
	_, err := q.db.Exec(ctx, updateTransportNode,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Coordinates,
		arg.Address,
		arg.CityID,
		arg.ImageID,
	)
	return err
}
