// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM "Country"
WHERE "id" = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM "Holiday"
WHERE "id" = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const findCountryByID = `-- name: FindCountryByID :one
SELECT "id", "name", "area", "population",
       "gdp", "currency", "visa_requirements",
       "description", "safety_tips", "best_season",
       "language", "phone_code", "religion",
       "capital_id", "image_id"
FROM "Country"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindCountryByID(ctx context.Context, id pgtype.UUID) (Country, error) {
	row := q.db.QueryRow(ctx, findCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.Population,
		&i.Gdp,
		&i.Currency,
		&i.VisaRequirements,
		&i.Description,
		&i.SafetyTips,
		&i.BestSeason,
		&i.Language,
		&i.PhoneCode,
		&i.Religion,
		&i.CapitalID,
		&i.ImageID,
	)
	return i, err
}

const findCountryByName = `-- name: FindCountryByName :one
SELECT "id", "name", "area", "population",
       "gdp", "currency", "visa_requirements",
       "description", "safety_tips", "best_season",
       "language", "phone_code", "religion",
       "capital_id", "image_id"
FROM "Country"
WHERE "name" = $1
LIMIT 1
`

func (q *Queries) FindCountryByName(ctx context.Context, name string) (Country, error) {
	row := q.db.QueryRow(ctx, findCountryByName, name)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.Population,
		&i.Gdp,
		&i.Currency,
		&i.VisaRequirements,
		&i.Description,
		&i.SafetyTips,
		&i.BestSeason,
		&i.Language,
		&i.PhoneCode,
		&i.Religion,
		&i.CapitalID,
		&i.ImageID,
	)
	return i, err
}

const findHolidayByID = `-- name: FindHolidayByID :one
SELECT "id", "name", "date",
    "description", "traditions",
    "history", "is_national",
    "country_id", "image_id"
FROM "Holiday"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindHolidayByID(ctx context.Context, id pgtype.UUID) (Holiday, error) {
	row := q.db.QueryRow(ctx, findHolidayByID, id)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Description,
		&i.Traditions,
		&i.History,
		&i.IsNational,
		&i.CountryID,
		&i.ImageID,
	)
	return i, err
}

const findHolidaysByCountry = `-- name: FindHolidaysByCountry :many
SELECT "id", "name", "date",
    "description", "traditions",
    "history", "is_national",
    "country_id", "image_id"
FROM "Holiday"
WHERE "country_id" = $1
LIMIT 30
`

func (q *Queries) FindHolidaysByCountry(ctx context.Context, countryID pgtype.UUID) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, findHolidaysByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Description,
			&i.Traditions,
			&i.History,
			&i.IsNational,
			&i.CountryID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findHolidaysByDate = `-- name: FindHolidaysByDate :many
SELECT "id", "name", "date",
    "description", "traditions",
    "history", "is_national",
    "country_id", "image_id"
FROM "Holiday"
WHERE "date" = $1
`

func (q *Queries) FindHolidaysByDate(ctx context.Context, date pgtype.Date) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, findHolidaysByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Description,
			&i.Traditions,
			&i.History,
			&i.IsNational,
			&i.CountryID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountries = `-- name: GetCountries :many
SELECT "id", "name", "area", "population",
       "gdp", "currency", "visa_requirements",
       "description", "safety_tips", "best_season",
       "language", "phone_code", "religion",
       "capital_id", "image_id"
FROM "Country"
LIMIT 200
`

func (q *Queries) GetCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, getCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Area,
			&i.Population,
			&i.Gdp,
			&i.Currency,
			&i.VisaRequirements,
			&i.Description,
			&i.SafetyTips,
			&i.BestSeason,
			&i.Language,
			&i.PhoneCode,
			&i.Religion,
			&i.CapitalID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCountry = `-- name: SaveCountry :one
INSERT INTO "Country" (
    "name",
    "area",
    "population",
    "gdp",
    "currency",
    "visa_requirements",
    "description",
    "safety_tips",
    "best_season",
    "language",
    "phone_code",
    "religion",
    "capital_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, 
$5, $6, 
$7, $8, 
$9, $10, 
$11, $12, 
$13, $14)
RETURNING "id"
`

type SaveCountryParams struct {
	Name             string         `json:"name"`
	Area             pgtype.Numeric `json:"area"`
	Population       pgtype.Int8    `json:"population"`
	Gdp              pgtype.Numeric `json:"gdp"`
	Currency         pgtype.Text    `json:"currency"`
	VisaRequirements pgtype.Text    `json:"visa_requirements"`
	Description      pgtype.Text    `json:"description"`
	SafetyTips       pgtype.Text    `json:"safety_tips"`
	BestSeason       pgtype.Text    `json:"best_season"`
	Language         pgtype.Text    `json:"language"`
	PhoneCode        pgtype.Text    `json:"phone_code"`
	Religion         pgtype.Text    `json:"religion"`
	CapitalID        pgtype.UUID    `json:"capital_id"`
	ImageID          pgtype.UUID    `json:"image_id"`
}

func (q *Queries) SaveCountry(ctx context.Context, arg SaveCountryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveCountry,
		arg.Name,
		arg.Area,
		arg.Population,
		arg.Gdp,
		arg.Currency,
		arg.VisaRequirements,
		arg.Description,
		arg.SafetyTips,
		arg.BestSeason,
		arg.Language,
		arg.PhoneCode,
		arg.Religion,
		arg.CapitalID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const saveHoliday = `-- name: SaveHoliday :one
INSERT INTO "Holiday" (
    "name",
    "date",
    "description",
    "traditions",
    "history",
    "is_national",
    "country_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, 
$5, $6, 
$7, $8)
RETURNING "id"
`

type SaveHolidayParams struct {
	Name        string      `json:"name"`
	Date        pgtype.Date `json:"date"`
	Description pgtype.Text `json:"description"`
	Traditions  pgtype.Text `json:"traditions"`
	History     pgtype.Text `json:"history"`
	IsNational  pgtype.Bool `json:"is_national"`
	CountryID   pgtype.UUID `json:"country_id"`
	ImageID     pgtype.UUID `json:"image_id"`
}

func (q *Queries) SaveHoliday(ctx context.Context, arg SaveHolidayParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveHoliday,
		arg.Name,
		arg.Date,
		arg.Description,
		arg.Traditions,
		arg.History,
		arg.IsNational,
		arg.CountryID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCountry = `-- name: UpdateCountry :exec
UPDATE "Country"
SET 
    "name" = $2,
    "area" = $3,
    "population" = $4,
    "gdp"  = $5,
    "currency" = $6,
    "visa_requirements" = $7,
    "description" = $8,
    "safety_tips" = $9,
    "best_season" = $10,
    "language" = $11,
    "phone_code" = $12,
    "religion" = $13,
    "capital_id" = $14,
    "image_id" = $15
WHERE "id" = $1
`

type UpdateCountryParams struct {
	ID               pgtype.UUID    `json:"id"`
	Name             string         `json:"name"`
	Area             pgtype.Numeric `json:"area"`
	Population       pgtype.Int8    `json:"population"`
	Gdp              pgtype.Numeric `json:"gdp"`
	Currency         pgtype.Text    `json:"currency"`
	VisaRequirements pgtype.Text    `json:"visa_requirements"`
	Description      pgtype.Text    `json:"description"`
	SafetyTips       pgtype.Text    `json:"safety_tips"`
	BestSeason       pgtype.Text    `json:"best_season"`
	Language         pgtype.Text    `json:"language"`
	PhoneCode        pgtype.Text    `json:"phone_code"`
	Religion         pgtype.Text    `json:"religion"`
	CapitalID        pgtype.UUID    `json:"capital_id"`
	ImageID          pgtype.UUID    `json:"image_id"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) error {
	_, err := q.db.Exec(ctx, updateCountry,
		arg.ID,
		arg.Name,
		arg.Area,
		arg.Population,
		arg.Gdp,
		arg.Currency,
		arg.VisaRequirements,
		arg.Description,
		arg.SafetyTips,
		arg.BestSeason,
		arg.Language,
		arg.PhoneCode,
		arg.Religion,
		arg.CapitalID,
		arg.ImageID,
	)
	return err
}

const updateHoliday = `-- name: UpdateHoliday :exec
UPDATE "Holiday"
SET 
    "name" = $2,
    "date" = $3,
    "description" = $4,
    "traditions" = $5,
    "history" = $6,
    "is_national" = $7,
    "country_id" = $8,
    "image_id" = $9
WHERE "id" = $1
`

type UpdateHolidayParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Date        pgtype.Date `json:"date"`
	Description pgtype.Text `json:"description"`
	Traditions  pgtype.Text `json:"traditions"`
	History     pgtype.Text `json:"history"`
	IsNational  pgtype.Bool `json:"is_national"`
	CountryID   pgtype.UUID `json:"country_id"`
	ImageID     pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) error {
	_, err := q.db.Exec(ctx, updateHoliday,
		arg.ID,
		arg.Name,
		arg.Date,
		arg.Description,
		arg.Traditions,
		arg.History,
		arg.IsNational,
		arg.CountryID,
		arg.ImageID,
	)
	return err
}
