// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favourites.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO "UserFavoritePlace" (user_id, place_id)
VALUES ($1, $2)
ON CONFLICT (user_id, place_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.PlaceID)
	return err
}

const getFavoritesByUser = `-- name: GetFavoritesByUser :many
SELECT 
    p.id, p.name, p.category, p.description, p.coordinates, p.address, 
    p.opening_hours, p.price_info, p.avg_visit_duration_min, p.avg_rating, 
    p.reviews_count, p.contact_phone, p.website, p.city_id, p.district_id, p.image_id,
    c.name AS city_name, c.id AS city_id,
    -- добавим также created_at из избранного
    ufp.created_at AS favorited_at
FROM "UserFavoritePlace" ufp
JOIN "Place" p ON p.id = ufp.place_id
LEFT JOIN "City" c ON c.id = p.city_id
WHERE ufp.user_id = $1
ORDER BY ufp.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFavoritesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetFavoritesByUserRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	Category            string           `json:"category"`
	Description         pgtype.Text      `json:"description"`
	Coordinates         pgtype.Point     `json:"coordinates"`
	Address             pgtype.Text      `json:"address"`
	OpeningHours        pgtype.Text      `json:"opening_hours"`
	PriceInfo           pgtype.Text      `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4      `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric   `json:"avg_rating"`
	ReviewsCount        pgtype.Int4      `json:"reviews_count"`
	ContactPhone        pgtype.Text      `json:"contact_phone"`
	Website             pgtype.Text      `json:"website"`
	CityID              pgtype.UUID      `json:"city_id"`
	DistrictID          pgtype.UUID      `json:"district_id"`
	ImageID             pgtype.UUID      `json:"image_id"`
	CityName            pgtype.Text      `json:"city_name"`
	CityID_2            pgtype.UUID      `json:"city_id_2"`
	FavoritedAt         pgtype.Timestamp `json:"favorited_at"`
}

func (q *Queries) GetFavoritesByUser(ctx context.Context, arg GetFavoritesByUserParams) ([]GetFavoritesByUserRow, error) {
	rows, err := q.db.Query(ctx, getFavoritesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFavoritesByUserRow
	for rows.Next() {
		var i GetFavoritesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Coordinates,
			&i.Address,
			&i.OpeningHours,
			&i.PriceInfo,
			&i.AvgVisitDurationMin,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.ContactPhone,
			&i.Website,
			&i.CityID,
			&i.DistrictID,
			&i.ImageID,
			&i.CityName,
			&i.CityID_2,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM "UserFavoritePlace"
WHERE user_id = $1 AND place_id = $2
`

type RemoveFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.PlaceID)
	return err
}
