// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgreSQL

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Population  pgtype.Int8  `json:"population"`
	IsCapital   pgtype.Bool  `json:"is_capital"`
	Coordinates pgtype.Point `json:"coordinates"`
	Description pgtype.Text  `json:"description"`
	Timezone    pgtype.Text  `json:"timezone"`
	TravelTips  pgtype.Text  `json:"travel_tips"`
	CountryID   pgtype.UUID  `json:"country_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

type CityDistrict struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Description pgtype.Text  `json:"description"`
	Coordinates pgtype.Point `json:"coordinates"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

type Country struct {
	ID               pgtype.UUID    `json:"id"`
	Name             string         `json:"name"`
	Area             pgtype.Numeric `json:"area"`
	Population       pgtype.Int8    `json:"population"`
	Gdp              pgtype.Numeric `json:"gdp"`
	Currency         pgtype.Text    `json:"currency"`
	VisaRequirements pgtype.Text    `json:"visa_requirements"`
	Description      pgtype.Text    `json:"description"`
	SafetyTips       pgtype.Text    `json:"safety_tips"`
	BestSeason       pgtype.Text    `json:"best_season"`
	Language         pgtype.Text    `json:"language"`
	PhoneCode        pgtype.Text    `json:"phone_code"`
	Religion         pgtype.Text    `json:"religion"`
	CapitalID        pgtype.UUID    `json:"capital_id"`
	ImageID          pgtype.UUID    `json:"image_id"`
}

type Holiday struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Date        pgtype.Date `json:"date"`
	Description pgtype.Text `json:"description"`
	Traditions  pgtype.Text `json:"traditions"`
	History     pgtype.Text `json:"history"`
	IsNational  pgtype.Bool `json:"is_national"`
	CountryID   pgtype.UUID `json:"country_id"`
	ImageID     pgtype.UUID `json:"image_id"`
}

type Place struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	Category            string           `json:"category"`
	Description         pgtype.Text      `json:"description"`
	Coordinates         pgtype.Point     `json:"coordinates"`
	Address             pgtype.Text      `json:"address"`
	OpeningHours        pgtype.Text      `json:"opening_hours"`
	PriceInfo           pgtype.Text      `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4      `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric   `json:"avg_rating"`
	ReviewsCount        pgtype.Int4      `json:"reviews_count"`
	ContactPhone        pgtype.Text      `json:"contact_phone"`
	Website             pgtype.Text      `json:"website"`
	CityID              pgtype.UUID      `json:"city_id"`
	DistrictID          pgtype.UUID      `json:"district_id"`
	ImageID             pgtype.UUID      `json:"image_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type Review struct {
	ID                pgtype.UUID      `json:"id"`
	Rating            int32            `json:"rating"`
	Comment           pgtype.Text      `json:"comment"`
	VisitDate         pgtype.Date      `json:"visit_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	IsModerated       pgtype.Bool      `json:"is_moderated"`
	IsApproved        pgtype.Bool      `json:"is_approved"`
	ModerationComment pgtype.Text      `json:"moderation_comment"`
	UserID            pgtype.UUID      `json:"user_id"`
	PlaceID           pgtype.UUID      `json:"place_id"`
	ImageID           pgtype.UUID      `json:"image_id"`
}

type StaticPage struct {
	ID              pgtype.UUID      `json:"id"`
	Slug            string           `json:"slug"`
	Title           string           `json:"title"`
	Content         pgtype.Text      `json:"content"`
	MetaDescription pgtype.Text      `json:"meta_description"`
	ImageUrl        pgtype.Text      `json:"image_url"`
	ImageAlt        pgtype.Text      `json:"image_alt"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	PublishedAt     pgtype.Timestamp `json:"published_at"`
	IsPublished     pgtype.Bool      `json:"is_published"`
}

type TransportNode struct {
	ID          pgtype.UUID  `json:"id"`
	Name        string       `json:"name"`
	Type        string       `json:"type"`
	Coordinates pgtype.Point `json:"coordinates"`
	Address     pgtype.Text  `json:"address"`
	CityID      pgtype.UUID  `json:"city_id"`
	ImageID     pgtype.UUID  `json:"image_id"`
}

type Trip struct {
	ID        pgtype.UUID      `json:"id"`
	Title     string           `json:"title"`
	StartDate pgtype.Date      `json:"start_date"`
	EndDate   pgtype.Date      `json:"end_date"`
	Budget    pgtype.Numeric   `json:"budget"`
	Status    pgtype.Text      `json:"status"`
	Notes     pgtype.Text      `json:"notes"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    pgtype.UUID      `json:"user_id"`
	ImageID   pgtype.UUID      `json:"image_id"`
}

type TripPlace struct {
	ID          pgtype.UUID    `json:"id"`
	DayNumber   int32          `json:"day_number"`
	ArrivalTime pgtype.Time    `json:"arrival_time"`
	DurationMin pgtype.Int4    `json:"duration_min"`
	Notes       pgtype.Text    `json:"notes"`
	VisitStatus pgtype.Text    `json:"visit_status"`
	ActualCost  pgtype.Numeric `json:"actual_cost"`
	TripID      pgtype.UUID    `json:"trip_id"`
	PlaceID     pgtype.UUID    `json:"place_id"`
}

type User struct {
	ID                 pgtype.UUID      `json:"id"`
	Role               string           `json:"role"`
	Username           string           `json:"username"`
	Email              string           `json:"email"`
	PasswordHash       string           `json:"password_hash"`
	Phone              pgtype.Text      `json:"phone"`
	RegisteredAt       pgtype.Timestamp `json:"registered_at"`
	BirthDate          pgtype.Date      `json:"birth_date"`
	CountryOfResidence pgtype.Text      `json:"country_of_residence"`
	AvatarUrl          pgtype.Text      `json:"avatar_url"`
	FavoriteCategories []string         `json:"favorite_categories"`
	IsBlocked          pgtype.Bool      `json:"is_blocked"`
	BlockedAt          pgtype.Timestamp `json:"blocked_at"`
	BlockReason        pgtype.Text      `json:"block_reason"`
	EmailVerified      pgtype.Bool      `json:"email_verified"`
	PhoneVerified      pgtype.Bool      `json:"phone_verified"`
	TwoFactorEnabled   pgtype.Bool      `json:"two_factor_enabled"`
	TwoFactorSecret    pgtype.Text      `json:"two_factor_secret"`
	BackupCodes        []string         `json:"backup_codes"`
}

type UserFavoritePlace struct {
	UserID    pgtype.UUID      `json:"user_id"`
	PlaceID   pgtype.UUID      `json:"place_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
