// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: place.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlace = `-- name: DeletePlace :exec
DELETE FROM "Place"
WHERE "id" = $1
`

func (q *Queries) DeletePlace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlace, id)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM "Review"
WHERE "id" = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const findPendingReviews = `-- name: FindPendingReviews :many
SELECT 
    r.id, r.rating, r.comment, r.visit_date, r.created_at,
    r.is_moderated, r.is_approved, r.moderation_comment,
    r.user_id, r.place_id, r.image_id,
    u.username
FROM "Review" r
JOIN "User" u ON u.id = r.user_id
WHERE r.is_moderated = false
ORDER BY r.created_at ASC
LIMIT $1 OFFSET $2
`

type FindPendingReviewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindPendingReviewsRow struct {
	ID                pgtype.UUID      `json:"id"`
	Rating            int32            `json:"rating"`
	Comment           pgtype.Text      `json:"comment"`
	VisitDate         pgtype.Date      `json:"visit_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	IsModerated       pgtype.Bool      `json:"is_moderated"`
	IsApproved        pgtype.Bool      `json:"is_approved"`
	ModerationComment pgtype.Text      `json:"moderation_comment"`
	UserID            pgtype.UUID      `json:"user_id"`
	PlaceID           pgtype.UUID      `json:"place_id"`
	ImageID           pgtype.UUID      `json:"image_id"`
	Username          string           `json:"username"`
}

func (q *Queries) FindPendingReviews(ctx context.Context, arg FindPendingReviewsParams) ([]FindPendingReviewsRow, error) {
	rows, err := q.db.Query(ctx, findPendingReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPendingReviewsRow
	for rows.Next() {
		var i FindPendingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.VisitDate,
			&i.CreatedAt,
			&i.IsModerated,
			&i.IsApproved,
			&i.ModerationComment,
			&i.UserID,
			&i.PlaceID,
			&i.ImageID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlaceByID = `-- name: FindPlaceByID :one
SELECT "id", "name",
    "category", "description",
    "coordinates", "address", 
    "opening_hours", "price_info",
    "avg_visit_duration_min", "avg_rating", "reviews_count",
    "contact_phone", "website",
    "city_id", "district_id",
    "image_id"
FROM "Place"
WHERE "id" = $1
LIMIT 1
`

type FindPlaceByIDRow struct {
	ID                  pgtype.UUID    `json:"id"`
	Name                string         `json:"name"`
	Category            string         `json:"category"`
	Description         pgtype.Text    `json:"description"`
	Coordinates         pgtype.Point   `json:"coordinates"`
	Address             pgtype.Text    `json:"address"`
	OpeningHours        pgtype.Text    `json:"opening_hours"`
	PriceInfo           pgtype.Text    `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4    `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric `json:"avg_rating"`
	ReviewsCount        pgtype.Int4    `json:"reviews_count"`
	ContactPhone        pgtype.Text    `json:"contact_phone"`
	Website             pgtype.Text    `json:"website"`
	CityID              pgtype.UUID    `json:"city_id"`
	DistrictID          pgtype.UUID    `json:"district_id"`
	ImageID             pgtype.UUID    `json:"image_id"`
}

func (q *Queries) FindPlaceByID(ctx context.Context, id pgtype.UUID) (FindPlaceByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlaceByID, id)
	var i FindPlaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Coordinates,
		&i.Address,
		&i.OpeningHours,
		&i.PriceInfo,
		&i.AvgVisitDurationMin,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.ContactPhone,
		&i.Website,
		&i.CityID,
		&i.DistrictID,
		&i.ImageID,
	)
	return i, err
}

const findPlacesByCategory = `-- name: FindPlacesByCategory :many
SELECT "id", "name",
    "category", "description",
    "coordinates", "address", 
    "opening_hours", "price_info",
    "avg_visit_duration_min", "avg_rating", "reviews_count",
    "contact_phone", "website",
    "city_id", "district_id",
    "image_id"
FROM "Place"
WHERE "category" = $1
`

type FindPlacesByCategoryRow struct {
	ID                  pgtype.UUID    `json:"id"`
	Name                string         `json:"name"`
	Category            string         `json:"category"`
	Description         pgtype.Text    `json:"description"`
	Coordinates         pgtype.Point   `json:"coordinates"`
	Address             pgtype.Text    `json:"address"`
	OpeningHours        pgtype.Text    `json:"opening_hours"`
	PriceInfo           pgtype.Text    `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4    `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric `json:"avg_rating"`
	ReviewsCount        pgtype.Int4    `json:"reviews_count"`
	ContactPhone        pgtype.Text    `json:"contact_phone"`
	Website             pgtype.Text    `json:"website"`
	CityID              pgtype.UUID    `json:"city_id"`
	DistrictID          pgtype.UUID    `json:"district_id"`
	ImageID             pgtype.UUID    `json:"image_id"`
}

func (q *Queries) FindPlacesByCategory(ctx context.Context, category string) ([]FindPlacesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, findPlacesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPlacesByCategoryRow
	for rows.Next() {
		var i FindPlacesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Coordinates,
			&i.Address,
			&i.OpeningHours,
			&i.PriceInfo,
			&i.AvgVisitDurationMin,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.ContactPhone,
			&i.Website,
			&i.CityID,
			&i.DistrictID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlacesByCity = `-- name: FindPlacesByCity :many
SELECT "id", "name",
    "category", "description",
    "coordinates", "address", 
    "opening_hours", "price_info",
    "avg_visit_duration_min", "avg_rating", "reviews_count",
    "contact_phone", "website",
    "city_id", "district_id",
    "image_id"
FROM "Place"
WHERE "city_id" = $1
`

type FindPlacesByCityRow struct {
	ID                  pgtype.UUID    `json:"id"`
	Name                string         `json:"name"`
	Category            string         `json:"category"`
	Description         pgtype.Text    `json:"description"`
	Coordinates         pgtype.Point   `json:"coordinates"`
	Address             pgtype.Text    `json:"address"`
	OpeningHours        pgtype.Text    `json:"opening_hours"`
	PriceInfo           pgtype.Text    `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4    `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric `json:"avg_rating"`
	ReviewsCount        pgtype.Int4    `json:"reviews_count"`
	ContactPhone        pgtype.Text    `json:"contact_phone"`
	Website             pgtype.Text    `json:"website"`
	CityID              pgtype.UUID    `json:"city_id"`
	DistrictID          pgtype.UUID    `json:"district_id"`
	ImageID             pgtype.UUID    `json:"image_id"`
}

func (q *Queries) FindPlacesByCity(ctx context.Context, cityID pgtype.UUID) ([]FindPlacesByCityRow, error) {
	rows, err := q.db.Query(ctx, findPlacesByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPlacesByCityRow
	for rows.Next() {
		var i FindPlacesByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Coordinates,
			&i.Address,
			&i.OpeningHours,
			&i.PriceInfo,
			&i.AvgVisitDurationMin,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.ContactPhone,
			&i.Website,
			&i.CityID,
			&i.DistrictID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReviewByID = `-- name: FindReviewByID :one
SELECT "id", "rating", "comment", "visit_date", "created_at",
       "is_moderated", "is_approved", "moderation_comment",
       "user_id", "place_id", "image_id"
FROM "Review"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindReviewByID(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, findReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Comment,
		&i.VisitDate,
		&i.CreatedAt,
		&i.IsModerated,
		&i.IsApproved,
		&i.ModerationComment,
		&i.UserID,
		&i.PlaceID,
		&i.ImageID,
	)
	return i, err
}

const findReviewsByPlace = `-- name: FindReviewsByPlace :many
SELECT "id", "rating", "comment", "visit_date", "created_at",
       "is_moderated", "is_approved", "moderation_comment",
       "user_id", "place_id", "image_id"
FROM "Review"
WHERE "place_id" = $1 AND is_approved = true
`

func (q *Queries) FindReviewsByPlace(ctx context.Context, placeID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, findReviewsByPlace, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.VisitDate,
			&i.CreatedAt,
			&i.IsModerated,
			&i.IsApproved,
			&i.ModerationComment,
			&i.UserID,
			&i.PlaceID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReviewsByUser = `-- name: FindReviewsByUser :many
SELECT "id", "rating", "comment", "visit_date", "created_at",
       "is_moderated", "is_approved", "moderation_comment",
       "user_id", "place_id", "image_id"
FROM "Review"
WHERE "user_id" = $1
`

func (q *Queries) FindReviewsByUser(ctx context.Context, userID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, findReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.VisitDate,
			&i.CreatedAt,
			&i.IsModerated,
			&i.IsApproved,
			&i.ModerationComment,
			&i.UserID,
			&i.PlaceID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReviewsByUserAndPlace = `-- name: FindReviewsByUserAndPlace :many
SELECT "id", "rating", "comment", "visit_date", "created_at",
       "is_moderated", "is_approved", "moderation_comment",
       "user_id", "place_id", "image_id"
FROM "Review"
WHERE "user_id" = $1 AND "place_id" = $2 AND is_approved = true
`

type FindReviewsByUserAndPlaceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

func (q *Queries) FindReviewsByUserAndPlace(ctx context.Context, arg FindReviewsByUserAndPlaceParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, findReviewsByUserAndPlace, arg.UserID, arg.PlaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.VisitDate,
			&i.CreatedAt,
			&i.IsModerated,
			&i.IsApproved,
			&i.ModerationComment,
			&i.UserID,
			&i.PlaceID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularPlacesReport = `-- name: GetPopularPlacesReport :many
SELECT 
    p.id,
    p.name,
    p.category,
    COALESCE(tp.trips_count, 0)::bigint AS trips_count,
    COALESCE(p.reviews_count, 0)::bigint AS reviews_count,
    COALESCE(p.avg_rating, 0)::numeric AS avg_rating
FROM "Place" p
LEFT JOIN (
    SELECT place_id, COUNT(*) AS trips_count
    FROM "TripPlace"
    GROUP BY place_id
) tp ON tp.place_id = p.id
ORDER BY trips_count DESC, p.reviews_count DESC
LIMIT $1::int
`

type GetPopularPlacesReportRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Category     string         `json:"category"`
	TripsCount   int64          `json:"trips_count"`
	ReviewsCount int64          `json:"reviews_count"`
	AvgRating    pgtype.Numeric `json:"avg_rating"`
}

func (q *Queries) GetPopularPlacesReport(ctx context.Context, limit int32) ([]GetPopularPlacesReportRow, error) {
	rows, err := q.db.Query(ctx, getPopularPlacesReport, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularPlacesReportRow
	for rows.Next() {
		var i GetPopularPlacesReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.TripsCount,
			&i.ReviewsCount,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateReview = `-- name: ModerateReview :exec
UPDATE "Review" 
SET 
    "is_moderated" = true,
    "is_approved" = $2,
    "moderation_comment" = $3
WHERE "id" = $1
`

type ModerateReviewParams struct {
	ID                pgtype.UUID `json:"id"`
	IsApproved        pgtype.Bool `json:"is_approved"`
	ModerationComment pgtype.Text `json:"moderation_comment"`
}

func (q *Queries) ModerateReview(ctx context.Context, arg ModerateReviewParams) error {
	_, err := q.db.Exec(ctx, moderateReview, arg.ID, arg.IsApproved, arg.ModerationComment)
	return err
}

const savePlace = `-- name: SavePlace :one
INSERT INTO "Place" (
    "name",
    "category",
    "description",
    "coordinates",
    "address", 
    "opening_hours",
    "price_info",
    "avg_visit_duration_min",
    "avg_rating",
    "reviews_count",
    "contact_phone",
    "website",
    "city_id",
    "district_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, 
$5, $6, 
$7, $8, 
$9, $10, 
$11, $12, 
$13, $14, $15)
RETURNING "id"
`

type SavePlaceParams struct {
	Name                string         `json:"name"`
	Category            string         `json:"category"`
	Description         pgtype.Text    `json:"description"`
	Coordinates         pgtype.Point   `json:"coordinates"`
	Address             pgtype.Text    `json:"address"`
	OpeningHours        pgtype.Text    `json:"opening_hours"`
	PriceInfo           pgtype.Text    `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4    `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric `json:"avg_rating"`
	ReviewsCount        pgtype.Int4    `json:"reviews_count"`
	ContactPhone        pgtype.Text    `json:"contact_phone"`
	Website             pgtype.Text    `json:"website"`
	CityID              pgtype.UUID    `json:"city_id"`
	DistrictID          pgtype.UUID    `json:"district_id"`
	ImageID             pgtype.UUID    `json:"image_id"`
}

func (q *Queries) SavePlace(ctx context.Context, arg SavePlaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, savePlace,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Coordinates,
		arg.Address,
		arg.OpeningHours,
		arg.PriceInfo,
		arg.AvgVisitDurationMin,
		arg.AvgRating,
		arg.ReviewsCount,
		arg.ContactPhone,
		arg.Website,
		arg.CityID,
		arg.DistrictID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const saveReview = `-- name: SaveReview :one
INSERT INTO "Review" (
    "rating",
    "comment",
    "visit_date",
    "user_id",
    "place_id",
    "image_id"
) VALUES
($1, $2, 
$3, $4, 
$5, $6)
RETURNING "id"
`

type SaveReviewParams struct {
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	VisitDate pgtype.Date `json:"visit_date"`
	UserID    pgtype.UUID `json:"user_id"`
	PlaceID   pgtype.UUID `json:"place_id"`
	ImageID   pgtype.UUID `json:"image_id"`
}

func (q *Queries) SaveReview(ctx context.Context, arg SaveReviewParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveReview,
		arg.Rating,
		arg.Comment,
		arg.VisitDate,
		arg.UserID,
		arg.PlaceID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePlace = `-- name: UpdatePlace :exec
UPDATE "Place" 
SET "name" = $2,
    "category" = $3,
    "description" = $4,
    "coordinates" = $5,
    "address" = $6,
    "opening_hours" = $7,
    "price_info" = $8,
    "avg_visit_duration_min" = $9,
    "avg_rating" = $10,
    "reviews_count" = $11,
    "contact_phone" = $12,
    "website" = $13,
    "city_id" = $14,
    "district_id" = $15,
    "image_id" = $16
WHERE "id" = $1
`

type UpdatePlaceParams struct {
	ID                  pgtype.UUID    `json:"id"`
	Name                string         `json:"name"`
	Category            string         `json:"category"`
	Description         pgtype.Text    `json:"description"`
	Coordinates         pgtype.Point   `json:"coordinates"`
	Address             pgtype.Text    `json:"address"`
	OpeningHours        pgtype.Text    `json:"opening_hours"`
	PriceInfo           pgtype.Text    `json:"price_info"`
	AvgVisitDurationMin pgtype.Int4    `json:"avg_visit_duration_min"`
	AvgRating           pgtype.Numeric `json:"avg_rating"`
	ReviewsCount        pgtype.Int4    `json:"reviews_count"`
	ContactPhone        pgtype.Text    `json:"contact_phone"`
	Website             pgtype.Text    `json:"website"`
	CityID              pgtype.UUID    `json:"city_id"`
	DistrictID          pgtype.UUID    `json:"district_id"`
	ImageID             pgtype.UUID    `json:"image_id"`
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) error {
	_, err := q.db.Exec(ctx, updatePlace,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Coordinates,
		arg.Address,
		arg.OpeningHours,
		arg.PriceInfo,
		arg.AvgVisitDurationMin,
		arg.AvgRating,
		arg.ReviewsCount,
		arg.ContactPhone,
		arg.Website,
		arg.CityID,
		arg.DistrictID,
		arg.ImageID,
	)
	return err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE "Place" 
SET 
    "avg_rating" = $2,
    "reviews_count" = $3
WHERE "id" = $1
`

type UpdateRatingParams struct {
	ID           pgtype.UUID    `json:"id"`
	AvgRating    pgtype.Numeric `json:"avg_rating"`
	ReviewsCount pgtype.Int4    `json:"reviews_count"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.Exec(ctx, updateRating, arg.ID, arg.AvgRating, arg.ReviewsCount)
	return err
}

const updateReview = `-- name: UpdateReview :exec
UPDATE "Review" 
SET "rating" = $2,
    "comment" = $3,
    "visit_date" = $4,
    "image_id" = $5
WHERE "id" = $1
`

type UpdateReviewParams struct {
	ID        pgtype.UUID `json:"id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	VisitDate pgtype.Date `json:"visit_date"`
	ImageID   pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.Exec(ctx, updateReview,
		arg.ID,
		arg.Rating,
		arg.Comment,
		arg.VisitDate,
		arg.ImageID,
	)
	return err
}
