// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	// =============================================
	// TripPlace (связь поездка – достопримечательность)
	// =============================================
	AddTripPlace(ctx context.Context, arg AddTripPlaceParams) (pgtype.UUID, error)
	BlockUser(ctx context.Context, arg BlockUserParams) error
	DeleteCity(ctx context.Context, id pgtype.UUID) error
	DeleteCountry(ctx context.Context, id pgtype.UUID) error
	DeleteDistrict(ctx context.Context, id pgtype.UUID) error
	DeleteHoliday(ctx context.Context, id pgtype.UUID) error
	DeletePlace(ctx context.Context, id pgtype.UUID) error
	DeleteReview(ctx context.Context, id pgtype.UUID) error
	DeleteStatic(ctx context.Context, id pgtype.UUID) error
	DeleteTransportNode(ctx context.Context, id pgtype.UUID) error
	DeleteTrip(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DisableTwoFactor(ctx context.Context, id pgtype.UUID) error
	EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) error
	FindAllUsers(ctx context.Context, arg FindAllUsersParams) ([]User, error)
	FindCitiesByCountry(ctx context.Context, countryID pgtype.UUID) ([]City, error)
	FindCityByID(ctx context.Context, id pgtype.UUID) (City, error)
	FindCityByName(ctx context.Context, name string) (City, error)
	FindCountryByID(ctx context.Context, id pgtype.UUID) (Country, error)
	FindCountryByName(ctx context.Context, name string) (Country, error)
	FindDistrictsByCity(ctx context.Context, cityID pgtype.UUID) ([]CityDistrict, error)
	FindHolidayByID(ctx context.Context, id pgtype.UUID) (Holiday, error)
	FindHolidaysByCountry(ctx context.Context, countryID pgtype.UUID) ([]Holiday, error)
	FindHolidaysByDate(ctx context.Context, date pgtype.Date) ([]Holiday, error)
	FindPendingReviews(ctx context.Context, arg FindPendingReviewsParams) ([]FindPendingReviewsRow, error)
	FindPlaceByID(ctx context.Context, id pgtype.UUID) (FindPlaceByIDRow, error)
	FindPlacesByCategory(ctx context.Context, category string) ([]FindPlacesByCategoryRow, error)
	FindPlacesByCity(ctx context.Context, cityID pgtype.UUID) ([]FindPlacesByCityRow, error)
	FindReviewByID(ctx context.Context, id pgtype.UUID) (Review, error)
	FindReviewsByPlace(ctx context.Context, placeID pgtype.UUID) ([]Review, error)
	FindReviewsByUser(ctx context.Context, userID pgtype.UUID) ([]Review, error)
	FindReviewsByUserAndPlace(ctx context.Context, arg FindReviewsByUserAndPlaceParams) ([]Review, error)
	FindStaticByID(ctx context.Context, id pgtype.UUID) (StaticPage, error)
	FindStaticPageBySlug(ctx context.Context, slug string) (StaticPage, error)
	FindTransportNodeByID(ctx context.Context, id pgtype.UUID) (TransportNode, error)
	FindTransportNodesByCity(ctx context.Context, cityID pgtype.UUID) ([]TransportNode, error)
	FindTripByID(ctx context.Context, id pgtype.UUID) (Trip, error)
	FindTripsByUser(ctx context.Context, userID pgtype.UUID) ([]Trip, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	GetCountries(ctx context.Context) ([]Country, error)
	GetFavoritesByUser(ctx context.Context, arg GetFavoritesByUserParams) ([]GetFavoritesByUserRow, error)
	GetPopularPlacesReport(ctx context.Context, limit int32) ([]GetPopularPlacesReportRow, error)
	GetTripPlaces(ctx context.Context, tripID pgtype.UUID) ([]TripPlace, error)
	GetTripStatisticsReport(ctx context.Context, arg GetTripStatisticsReportParams) ([]GetTripStatisticsReportRow, error)
	GetUserActivityReport(ctx context.Context, arg GetUserActivityReportParams) ([]GetUserActivityReportRow, error)
	ModerateReview(ctx context.Context, arg ModerateReviewParams) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	RemoveTripPlace(ctx context.Context, arg RemoveTripPlaceParams) error
	SaveCity(ctx context.Context, arg SaveCityParams) (pgtype.UUID, error)
	SaveCountry(ctx context.Context, arg SaveCountryParams) (pgtype.UUID, error)
	SaveDistrict(ctx context.Context, arg SaveDistrictParams) (pgtype.UUID, error)
	SaveHoliday(ctx context.Context, arg SaveHolidayParams) (pgtype.UUID, error)
	SavePlace(ctx context.Context, arg SavePlaceParams) (pgtype.UUID, error)
	SaveReview(ctx context.Context, arg SaveReviewParams) (pgtype.UUID, error)
	SaveStatic(ctx context.Context, arg SaveStaticParams) (pgtype.UUID, error)
	SaveTransportNode(ctx context.Context, arg SaveTransportNodeParams) (pgtype.UUID, error)
	SaveTrip(ctx context.Context, arg SaveTripParams) (pgtype.UUID, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (pgtype.UUID, error)
	SearchCities(ctx context.Context, arg SearchCitiesParams) ([]City, error)
	UnblockUser(ctx context.Context, id pgtype.UUID) error
	UpdateCity(ctx context.Context, arg UpdateCityParams) error
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) error
	UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) error
	UpdateEmailVerified(ctx context.Context, arg UpdateEmailVerifiedParams) error
	UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) error
	UpdatePhoneVerified(ctx context.Context, arg UpdatePhoneVerifiedParams) error
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) error
	UpdateRating(ctx context.Context, arg UpdateRatingParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateStatic(ctx context.Context, arg UpdateStaticParams) error
	UpdateTransportNode(ctx context.Context, arg UpdateTransportNodeParams) error
	UpdateTrip(ctx context.Context, arg UpdateTripParams) error
	UpdateTripPlace(ctx context.Context, arg UpdateTripPlaceParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
