// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: static.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStatic = `-- name: DeleteStatic :exec
DELETE FROM "StaticPage"
WHERE "id" = $1
`

func (q *Queries) DeleteStatic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatic, id)
	return err
}

const findStaticByID = `-- name: FindStaticByID :one
SELECT "id", "slug", "title", "content", "meta_description",
       "image_url", "image_alt", "updated_at", "published_at", "is_published"
FROM "StaticPage"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindStaticByID(ctx context.Context, id pgtype.UUID) (StaticPage, error) {
	row := q.db.QueryRow(ctx, findStaticByID, id)
	var i StaticPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.MetaDescription,
		&i.ImageUrl,
		&i.ImageAlt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsPublished,
	)
	return i, err
}

const findStaticPageBySlug = `-- name: FindStaticPageBySlug :one
SELECT "id", "slug", "title", "content", "meta_description",
       "image_url", "image_alt", "updated_at", "published_at", "is_published"
FROM "StaticPage" 
WHERE "slug" = $1 
LIMIT 1
`

func (q *Queries) FindStaticPageBySlug(ctx context.Context, slug string) (StaticPage, error) {
	row := q.db.QueryRow(ctx, findStaticPageBySlug, slug)
	var i StaticPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.MetaDescription,
		&i.ImageUrl,
		&i.ImageAlt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsPublished,
	)
	return i, err
}

const saveStatic = `-- name: SaveStatic :one
INSERT INTO "StaticPage" (
    "id",
    "slug",
    "title",
    "content",
    "meta_description",
    "image_url",
    "image_alt",
    "is_published"
) VALUES
($1, $2, 
$3, $4, 
$5, $6, 
$7, $8)
RETURNING "id"
`

type SaveStaticParams struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	Content         pgtype.Text `json:"content"`
	MetaDescription pgtype.Text `json:"meta_description"`
	ImageUrl        pgtype.Text `json:"image_url"`
	ImageAlt        pgtype.Text `json:"image_alt"`
	IsPublished     pgtype.Bool `json:"is_published"`
}

func (q *Queries) SaveStatic(ctx context.Context, arg SaveStaticParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveStatic,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.MetaDescription,
		arg.ImageUrl,
		arg.ImageAlt,
		arg.IsPublished,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateStatic = `-- name: UpdateStatic :exec
UPDATE "StaticPage" 
SET "slug" = $2,
    "title" = $3,
    "content" = $4,
    "meta_description" = $5,
    "image_url" = $6,
    "image_alt" = $7,
    "is_published" = $8
WHERE "id" = $1
`

type UpdateStaticParams struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	Content         pgtype.Text `json:"content"`
	MetaDescription pgtype.Text `json:"meta_description"`
	ImageUrl        pgtype.Text `json:"image_url"`
	ImageAlt        pgtype.Text `json:"image_alt"`
	IsPublished     pgtype.Bool `json:"is_published"`
}

func (q *Queries) UpdateStatic(ctx context.Context, arg UpdateStaticParams) error {
	_, err := q.db.Exec(ctx, updateStatic,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.MetaDescription,
		arg.ImageUrl,
		arg.ImageAlt,
		arg.IsPublished,
	)
	return err
}
