// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTripPlace = `-- name: AddTripPlace :one

INSERT INTO "TripPlace" (
    "day_number",
    "arrival_time",
    "duration_min",
    "notes",
    "visit_status",
    "actual_cost",
    "trip_id",
    "place_id"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING "id"
`

type AddTripPlaceParams struct {
	DayNumber   int32          `json:"day_number"`
	ArrivalTime pgtype.Time    `json:"arrival_time"`
	DurationMin pgtype.Int4    `json:"duration_min"`
	Notes       pgtype.Text    `json:"notes"`
	VisitStatus pgtype.Text    `json:"visit_status"`
	ActualCost  pgtype.Numeric `json:"actual_cost"`
	TripID      pgtype.UUID    `json:"trip_id"`
	PlaceID     pgtype.UUID    `json:"place_id"`
}

// =============================================
// TripPlace (связь поездка – достопримечательность)
// =============================================
func (q *Queries) AddTripPlace(ctx context.Context, arg AddTripPlaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addTripPlace,
		arg.DayNumber,
		arg.ArrivalTime,
		arg.DurationMin,
		arg.Notes,
		arg.VisitStatus,
		arg.ActualCost,
		arg.TripID,
		arg.PlaceID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM "Trip"
WHERE "id" = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrip, id)
	return err
}

const findTripByID = `-- name: FindTripByID :one
SELECT "id", "title", "start_date", "end_date", "budget",
       "status", "notes", "created_at", "user_id", "image_id"
FROM "Trip"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindTripByID(ctx context.Context, id pgtype.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, findTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UserID,
		&i.ImageID,
	)
	return i, err
}

const findTripsByUser = `-- name: FindTripsByUser :many
SELECT "id", "title", "start_date", "end_date", "budget",
       "status", "notes", "created_at", "user_id", "image_id"
FROM "Trip"
WHERE "user_id" = $1
ORDER BY "start_date" DESC
`

func (q *Queries) FindTripsByUser(ctx context.Context, userID pgtype.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, findTripsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Budget,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UserID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripPlaces = `-- name: GetTripPlaces :many
SELECT "id", "day_number", "arrival_time", "duration_min",
       "notes", "visit_status", "actual_cost", "trip_id", "place_id"
FROM "TripPlace"
WHERE "trip_id" = $1
ORDER BY "day_number", "arrival_time"
`

func (q *Queries) GetTripPlaces(ctx context.Context, tripID pgtype.UUID) ([]TripPlace, error) {
	rows, err := q.db.Query(ctx, getTripPlaces, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripPlace
	for rows.Next() {
		var i TripPlace
		if err := rows.Scan(
			&i.ID,
			&i.DayNumber,
			&i.ArrivalTime,
			&i.DurationMin,
			&i.Notes,
			&i.VisitStatus,
			&i.ActualCost,
			&i.TripID,
			&i.PlaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripStatisticsReport = `-- name: GetTripStatisticsReport :many
SELECT 
    t.id,
    t.title,
    t.user_id,
    t.start_date,
    t.end_date,
    COALESCE(tp.places_count, 0)::bigint AS places_count,
    COALESCE(tp.total_cost, 0)::numeric AS total_cost
FROM "Trip" t
LEFT JOIN (
    SELECT trip_id, COUNT(*) AS places_count, SUM(COALESCE(actual_cost, 0)) AS total_cost
    FROM "TripPlace"
    GROUP BY trip_id
) tp ON tp.trip_id = t.id
WHERE ($1::text IS NULL OR $1::text = '' OR t.start_date >= $1::timestamp)
  AND ($2::text IS NULL OR $2::text = '' OR t.end_date <= $2::timestamp)
ORDER BY t.start_date DESC
LIMIT $3::int
`

type GetTripStatisticsReportParams struct {
	DateFrom pgtype.Text `json:"date_from"`
	DateTo   pgtype.Text `json:"date_to"`
	Limit    int32       `json:"limit"`
}

type GetTripStatisticsReportRow struct {
	ID          pgtype.UUID    `json:"id"`
	Title       string         `json:"title"`
	UserID      pgtype.UUID    `json:"user_id"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	PlacesCount int64          `json:"places_count"`
	TotalCost   pgtype.Numeric `json:"total_cost"`
}

func (q *Queries) GetTripStatisticsReport(ctx context.Context, arg GetTripStatisticsReportParams) ([]GetTripStatisticsReportRow, error) {
	rows, err := q.db.Query(ctx, getTripStatisticsReport, arg.DateFrom, arg.DateTo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripStatisticsReportRow
	for rows.Next() {
		var i GetTripStatisticsReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.PlacesCount,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTripPlace = `-- name: RemoveTripPlace :exec
DELETE FROM "TripPlace"
WHERE "trip_id" = $1 AND "place_id" = $2
`

type RemoveTripPlaceParams struct {
	TripID  pgtype.UUID `json:"trip_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

func (q *Queries) RemoveTripPlace(ctx context.Context, arg RemoveTripPlaceParams) error {
	_, err := q.db.Exec(ctx, removeTripPlace, arg.TripID, arg.PlaceID)
	return err
}

const saveTrip = `-- name: SaveTrip :one
INSERT INTO "Trip" (
    "title",
    "start_date",
    "end_date",
    "budget",
    "status",
    "notes",
    "user_id",
    "image_id"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING "id"
`

type SaveTripParams struct {
	Title     string         `json:"title"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	Budget    pgtype.Numeric `json:"budget"`
	Status    pgtype.Text    `json:"status"`
	Notes     pgtype.Text    `json:"notes"`
	UserID    pgtype.UUID    `json:"user_id"`
	ImageID   pgtype.UUID    `json:"image_id"`
}

func (q *Queries) SaveTrip(ctx context.Context, arg SaveTripParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveTrip,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
		arg.Status,
		arg.Notes,
		arg.UserID,
		arg.ImageID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE "Trip"
SET
    "title" = $2,
    "start_date" = $3,
    "end_date" = $4,
    "budget" = $5,
    "status" = $6,
    "notes" = $7,
    "image_id" = $8
WHERE "id" = $1
`

type UpdateTripParams struct {
	ID        pgtype.UUID    `json:"id"`
	Title     string         `json:"title"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	Budget    pgtype.Numeric `json:"budget"`
	Status    pgtype.Text    `json:"status"`
	Notes     pgtype.Text    `json:"notes"`
	ImageID   pgtype.UUID    `json:"image_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.Exec(ctx, updateTrip,
		arg.ID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
		arg.Status,
		arg.Notes,
		arg.ImageID,
	)
	return err
}

const updateTripPlace = `-- name: UpdateTripPlace :exec
UPDATE "TripPlace"
SET
    "day_number" = $2,
    "arrival_time" = $3,
    "duration_min" = $4,
    "notes" = $5,
    "visit_status" = $6,
    "actual_cost" = $7
WHERE "id" = $1
`

type UpdateTripPlaceParams struct {
	ID          pgtype.UUID    `json:"id"`
	DayNumber   int32          `json:"day_number"`
	ArrivalTime pgtype.Time    `json:"arrival_time"`
	DurationMin pgtype.Int4    `json:"duration_min"`
	Notes       pgtype.Text    `json:"notes"`
	VisitStatus pgtype.Text    `json:"visit_status"`
	ActualCost  pgtype.Numeric `json:"actual_cost"`
}

func (q *Queries) UpdateTripPlace(ctx context.Context, arg UpdateTripPlaceParams) error {
	_, err := q.db.Exec(ctx, updateTripPlace,
		arg.ID,
		arg.DayNumber,
		arg.ArrivalTime,
		arg.DurationMin,
		arg.Notes,
		arg.VisitStatus,
		arg.ActualCost,
	)
	return err
}
