// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgreSQL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :exec
UPDATE "User"
SET
    "is_blocked" = true,
    "blocked_at" = CURRENT_TIMESTAMP,
    "block_reason" = $2
WHERE "id" = $1
`

type BlockUserParams struct {
	ID          pgtype.UUID `json:"id"`
	BlockReason pgtype.Text `json:"block_reason"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.ID, arg.BlockReason)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "User"
WHERE "id" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableTwoFactor = `-- name: DisableTwoFactor :exec
UPDATE "User"
SET "two_factor_enabled" = false,
    "two_factor_secret" = NULL,
    "backup_codes" = NULL
WHERE "id" = $1
`

func (q *Queries) DisableTwoFactor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTwoFactor, id)
	return err
}

const enableTwoFactor = `-- name: EnableTwoFactor :exec
UPDATE "User"
SET "two_factor_enabled" = true,
    "two_factor_secret" = $2,
    "backup_codes" = $3
WHERE "id" = $1
`

type EnableTwoFactorParams struct {
	ID              pgtype.UUID `json:"id"`
	TwoFactorSecret pgtype.Text `json:"two_factor_secret"`
	BackupCodes     []string    `json:"backup_codes"`
}

func (q *Queries) EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) error {
	_, err := q.db.Exec(ctx, enableTwoFactor, arg.ID, arg.TwoFactorSecret, arg.BackupCodes)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT "id", "role", "username", "email", "password_hash", "phone", "registered_at", "birth_date",
       "country_of_residence", "avatar_url", "favorite_categories",
       "is_blocked", "blocked_at", "block_reason",
       "email_verified", "phone_verified", "two_factor_enabled", "two_factor_secret", "backup_codes"
FROM "User"
WHERE ($1::text = '' OR username ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type FindAllUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) FindAllUsers(ctx context.Context, arg FindAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Phone,
			&i.RegisteredAt,
			&i.BirthDate,
			&i.CountryOfResidence,
			&i.AvatarUrl,
			&i.FavoriteCategories,
			&i.IsBlocked,
			&i.BlockedAt,
			&i.BlockReason,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.TwoFactorEnabled,
			&i.TwoFactorSecret,
			&i.BackupCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT "id", "role", "username", "email", "password_hash",
       "phone", "registered_at", "birth_date", "country_of_residence",
       "avatar_url", "favorite_categories",
       "is_blocked", "blocked_at", "block_reason",
       "email_verified", "phone_verified", "two_factor_enabled",
       "two_factor_secret", "backup_codes"
FROM "User"
WHERE "email" = $1
LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.RegisteredAt,
		&i.BirthDate,
		&i.CountryOfResidence,
		&i.AvatarUrl,
		&i.FavoriteCategories,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockReason,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.BackupCodes,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT "id", "role", "username", "email", "password_hash",
       "phone", "registered_at", "birth_date", "country_of_residence",
       "avatar_url", "favorite_categories",
       "is_blocked", "blocked_at", "block_reason",
       "email_verified", "phone_verified", "two_factor_enabled",
       "two_factor_secret", "backup_codes"
FROM "User"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.RegisteredAt,
		&i.BirthDate,
		&i.CountryOfResidence,
		&i.AvatarUrl,
		&i.FavoriteCategories,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockReason,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.BackupCodes,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT "id", "role", "username", "email", "password_hash",
       "phone", "registered_at", "birth_date", "country_of_residence",
       "avatar_url", "favorite_categories",
       "is_blocked", "blocked_at", "block_reason",
       "email_verified", "phone_verified", "two_factor_enabled",
       "two_factor_secret", "backup_codes"
FROM "User"
WHERE "username" = $1
LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.RegisteredAt,
		&i.BirthDate,
		&i.CountryOfResidence,
		&i.AvatarUrl,
		&i.FavoriteCategories,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockReason,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.BackupCodes,
	)
	return i, err
}

const getUserActivityReport = `-- name: GetUserActivityReport :many
SELECT 
    u.id,
    u.username,
    COALESCE(t.trips_created, 0)::bigint AS trips_created,
    COALESCE(r.reviews_written, 0)::bigint AS reviews_written,
    GREATEST(
        COALESCE(t.last_trip, '1970-01-01'::timestamp), 
        COALESCE(r.last_review, '1970-01-01'::timestamp)
    ) AS last_active
FROM "User" u
LEFT JOIN (
    SELECT user_id, COUNT(*) AS trips_created, MAX(created_at) AS last_trip
    FROM "Trip"
    WHERE ($1::text IS NULL OR $1::text = '' OR created_at >= $1::timestamp)
      AND ($2::text IS NULL OR $2::text = '' OR created_at <= $2::timestamp)
    GROUP BY user_id
) t ON t.user_id = u.id
LEFT JOIN (
    SELECT user_id, COUNT(*) AS reviews_written, MAX(created_at) AS last_review
    FROM "Review"
    WHERE ($1::text IS NULL OR $1::text = '' OR created_at >= $1::timestamp)
      AND ($2::text IS NULL OR $2::text = '' OR created_at <= $2::timestamp)
    GROUP BY user_id
) r ON r.user_id = u.id
ORDER BY last_active DESC
LIMIT $3::int
`

type GetUserActivityReportParams struct {
	DateFrom pgtype.Text `json:"date_from"`
	DateTo   pgtype.Text `json:"date_to"`
	Limit    int32       `json:"limit"`
}

type GetUserActivityReportRow struct {
	ID             pgtype.UUID `json:"id"`
	Username       string      `json:"username"`
	TripsCreated   int64       `json:"trips_created"`
	ReviewsWritten int64       `json:"reviews_written"`
	LastActive     interface{} `json:"last_active"`
}

func (q *Queries) GetUserActivityReport(ctx context.Context, arg GetUserActivityReportParams) ([]GetUserActivityReportRow, error) {
	rows, err := q.db.Query(ctx, getUserActivityReport, arg.DateFrom, arg.DateTo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivityReportRow
	for rows.Next() {
		var i GetUserActivityReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TripsCreated,
			&i.ReviewsWritten,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUser = `-- name: SaveUser :one
INSERT INTO "User" (
    "role",
    "username",
    "email",
    "password_hash",
    "phone",
    "birth_date",
    "country_of_residence",
    "avatar_url",
    "favorite_categories",
    "email_verified",
    "phone_verified",
    "two_factor_enabled",
    "two_factor_secret",
    "backup_codes"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, false, false, false, NULL, NULL)
RETURNING "id"
`

type SaveUserParams struct {
	Role               string      `json:"role"`
	Username           string      `json:"username"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	Phone              pgtype.Text `json:"phone"`
	BirthDate          pgtype.Date `json:"birth_date"`
	CountryOfResidence pgtype.Text `json:"country_of_residence"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	FavoriteCategories []string    `json:"favorite_categories"`
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.Role,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.BirthDate,
		arg.CountryOfResidence,
		arg.AvatarUrl,
		arg.FavoriteCategories,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const unblockUser = `-- name: UnblockUser :exec
UPDATE "User"
SET
    "is_blocked" = false,
    "blocked_at" = NULL,
    "block_reason" = NULL
WHERE "id" = $1
`

func (q *Queries) UnblockUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unblockUser, id)
	return err
}

const updateEmailVerified = `-- name: UpdateEmailVerified :exec
UPDATE "User"
SET "email_verified" = $2
WHERE "id" = $1
`

type UpdateEmailVerifiedParams struct {
	ID            pgtype.UUID `json:"id"`
	EmailVerified pgtype.Bool `json:"email_verified"`
}

func (q *Queries) UpdateEmailVerified(ctx context.Context, arg UpdateEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const updatePhoneVerified = `-- name: UpdatePhoneVerified :exec
UPDATE "User"
SET "phone_verified" = $2
WHERE "id" = $1
`

type UpdatePhoneVerifiedParams struct {
	ID            pgtype.UUID `json:"id"`
	PhoneVerified pgtype.Bool `json:"phone_verified"`
}

func (q *Queries) UpdatePhoneVerified(ctx context.Context, arg UpdatePhoneVerifiedParams) error {
	_, err := q.db.Exec(ctx, updatePhoneVerified, arg.ID, arg.PhoneVerified)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "User"
SET
    "role" = $2,
    "username" = $3,
    "email" = $4,
    "password_hash" = $5,
    "phone" = $6,
    "birth_date" = $7,
    "country_of_residence" = $8,
    "avatar_url" = $9,
    "favorite_categories" = $10
WHERE "id" = $1
`

type UpdateUserParams struct {
	ID                 pgtype.UUID `json:"id"`
	Role               string      `json:"role"`
	Username           string      `json:"username"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	Phone              pgtype.Text `json:"phone"`
	BirthDate          pgtype.Date `json:"birth_date"`
	CountryOfResidence pgtype.Text `json:"country_of_residence"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	FavoriteCategories []string    `json:"favorite_categories"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Role,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.BirthDate,
		arg.CountryOfResidence,
		arg.AvatarUrl,
		arg.FavoriteCategories,
	)
	return err
}
