// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GenerateReportRequestFormat.
const (
	Csv  GenerateReportRequestFormat = "csv"
	Json GenerateReportRequestFormat = "json"
)

// Valid indicates whether the value is a known member of the GenerateReportRequestFormat enum.
func (e GenerateReportRequestFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Json:
		return true
	default:
		return false
	}
}

// Defines values for GenerateReportRequestReportType.
const (
	PopularPlaces  GenerateReportRequestReportType = "popular_places"
	TripStatistics GenerateReportRequestReportType = "trip_statistics"
	UserActivity   GenerateReportRequestReportType = "user_activity"
)

// Valid indicates whether the value is a known member of the GenerateReportRequestReportType enum.
func (e GenerateReportRequestReportType) Valid() bool {
	switch e {
	case PopularPlaces:
		return true
	case TripStatistics:
		return true
	case UserActivity:
		return true
	default:
		return false
	}
}

// Defines values for GetUserProfileResponseRole.
const (
	Analyst   GetUserProfileResponseRole = "analyst"
	Moderator GetUserProfileResponseRole = "moderator"
	User      GetUserProfileResponseRole = "user"
)

// Valid indicates whether the value is a known member of the GetUserProfileResponseRole enum.
func (e GetUserProfileResponseRole) Valid() bool {
	switch e {
	case Analyst:
		return true
	case Moderator:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for TransportNodeResponseNodeType.
const (
	Airport      TransportNodeResponseNodeType = "airport"
	BusStation   TransportNodeResponseNodeType = "bus_station"
	Port         TransportNodeResponseNodeType = "port"
	TrainStation TransportNodeResponseNodeType = "train_station"
)

// Valid indicates whether the value is a known member of the TransportNodeResponseNodeType enum.
func (e TransportNodeResponseNodeType) Valid() bool {
	switch e {
	case Airport:
		return true
	case BusStation:
		return true
	case Port:
		return true
	case TrainStation:
		return true
	default:
		return false
	}
}

// Defines values for GetPlacesParamsSortBy.
const (
	Name   GetPlacesParamsSortBy = "name"
	Rating GetPlacesParamsSortBy = "rating"
	Visits GetPlacesParamsSortBy = "visits"
)

// Valid indicates whether the value is a known member of the GetPlacesParamsSortBy enum.
func (e GetPlacesParamsSortBy) Valid() bool {
	switch e {
	case Name:
		return true
	case Rating:
		return true
	case Visits:
		return true
	default:
		return false
	}
}

// AddPlaceToTripRequest defines model for AddPlaceToTripRequest.
type AddPlaceToTripRequest struct {
	ArrivalTime *time.Time         `json:"arrivalTime,omitempty"`
	DayNumber   int                `json:"dayNumber"`
	DurationMin *int               `json:"durationMin,omitempty"`
	Notes       *string            `json:"notes,omitempty"`
	PlaceId     openapi_types.UUID `json:"placeId"`
}

// CityResponse defines model for CityResponse.
type CityResponse struct {
	Coordinates *Coordinates        `json:"coordinates,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl    *string             `json:"imageUrl,omitempty"`
	IsCapital   *bool               `json:"isCapital,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Population  *int64              `json:"population,omitempty"`
	Timezone    *string             `json:"timezone,omitempty"`
}

// Coordinates defines model for Coordinates.
type Coordinates struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// CountryResponse defines model for CountryResponse.
type CountryResponse struct {
	Area       *float32            `json:"area,omitempty"`
	Capital    *string             `json:"capital,omitempty"`
	Currency   *string             `json:"currency,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl   *string             `json:"imageUrl,omitempty"`
	Language   *string             `json:"language,omitempty"`
	Name       *string             `json:"name,omitempty"`
	PhoneCode  *string             `json:"phoneCode,omitempty"`
	Population *int64              `json:"population,omitempty"`
}

// CreateReviewRequest defines model for CreateReviewRequest.
type CreateReviewRequest struct {
	Comment   string             `json:"comment"`
	ImageUrl  *string            `json:"imageUrl,omitempty"`
	Rating    int                `json:"rating"`
	VisitDate openapi_types.Date `json:"visitDate"`
}

// CreateReviewResponse defines model for CreateReviewResponse.
type CreateReviewResponse struct {
	Comment     *string             `json:"comment,omitempty"`
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsApproved  *bool               `json:"isApproved,omitempty"`
	IsModerated *bool               `json:"isModerated,omitempty"`
	Rating      *int                `json:"rating,omitempty"`
	VisitDate   *openapi_types.Date `json:"visitDate,omitempty"`
}

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	Budget    *float32           `json:"budget,omitempty"`
	EndDate   openapi_types.Date `json:"endDate"`
	Notes     *string            `json:"notes,omitempty"`
	StartDate openapi_types.Date `json:"startDate"`
	Title     string             `json:"title"`
}

// CreateTripResponse defines model for CreateTripResponse.
type CreateTripResponse struct {
	Budget    *float32            `json:"budget,omitempty"`
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *string             `json:"status,omitempty"`
	Title     *string             `json:"title,omitempty"`
}

// DistrictResponse defines model for DistrictResponse.
type DistrictResponse struct {
	CityId      *openapi_types.UUID `json:"cityId,omitempty"`
	Coordinates *Coordinates        `json:"coordinates,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	ImageId     *openapi_types.UUID `json:"imageId,omitempty"`
	Name        *string             `json:"name,omitempty"`
}

// EnableTwoFactorRequest defines model for EnableTwoFactorRequest.
type EnableTwoFactorRequest struct {
	Code   string             `json:"code"`
	Secret string             `json:"secret"`
	UserId openapi_types.UUID `json:"userId"`
}

// EnableTwoFactorResponse defines model for EnableTwoFactorResponse.
type EnableTwoFactorResponse struct {
	BackupCodes *[]string `json:"backupCodes,omitempty"`
	OtpauthUri  *string   `json:"otpauthUri,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FavouriteRequest defines model for FavouriteRequest.
type FavouriteRequest struct {
	PlaceId openapi_types.UUID `json:"placeId"`
}

// GenerateReportRequest defines model for GenerateReportRequest.
type GenerateReportRequest struct {
	DateFrom   *openapi_types.Date             `json:"dateFrom,omitempty"`
	DateTo     *openapi_types.Date             `json:"dateTo,omitempty"`
	Format     GenerateReportRequestFormat     `json:"format"`
	Limit      *int                            `json:"limit,omitempty"`
	ReportType GenerateReportRequestReportType `json:"reportType"`
}

// GenerateReportRequestFormat defines model for GenerateReportRequest.Format.
type GenerateReportRequestFormat string

// GenerateReportRequestReportType defines model for GenerateReportRequest.ReportType.
type GenerateReportRequestReportType string

// GetCityResponse defines model for GetCityResponse.
type GetCityResponse struct {
	Coordinates *Coordinates        `json:"coordinates,omitempty"`
	CountryId   *openapi_types.UUID `json:"countryId,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	ImageId     *openapi_types.UUID `json:"imageId,omitempty"`
	ImageUrl    *string             `json:"imageUrl,omitempty"`
	IsCapital   *bool               `json:"isCapital,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Population  *int64              `json:"population,omitempty"`
	Timezone    *string             `json:"timezone,omitempty"`
	TravelTips  *string             `json:"travelTips,omitempty"`
}

// GetCountryResponse defines model for GetCountryResponse.
type GetCountryResponse struct {
	Area             *float32            `json:"area,omitempty"`
	BestSeason       *string             `json:"bestSeason,omitempty"`
	CapitalId        *openapi_types.UUID `json:"capitalId,omitempty"`
	CapitalName      *string             `json:"capitalName,omitempty"`
	Currency         *string             `json:"currency,omitempty"`
	Description      *string             `json:"description,omitempty"`
	Gdp              *float32            `json:"gdp,omitempty"`
	Holidays         *[]HolidayResponse  `json:"holidays,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl         *string             `json:"imageUrl,omitempty"`
	Language         *string             `json:"language,omitempty"`
	Name             *string             `json:"name,omitempty"`
	PhoneCode        *string             `json:"phoneCode,omitempty"`
	Population       *int64              `json:"population,omitempty"`
	Religion         *string             `json:"religion,omitempty"`
	SafetyTips       *string             `json:"safetyTips,omitempty"`
	VisaRequirements *string             `json:"visaRequirements,omitempty"`
}

// GetTripResponse defines model for GetTripResponse.
type GetTripResponse struct {
	Budget    *float32             `json:"budget,omitempty"`
	EndDate   *openapi_types.Date  `json:"endDate,omitempty"`
	Id        *openapi_types.UUID  `json:"id,omitempty"`
	Notes     *string              `json:"notes,omitempty"`
	Places    *[]TripPlaceResponse `json:"places,omitempty"`
	StartDate *openapi_types.Date  `json:"startDate,omitempty"`
	Status    *string              `json:"status,omitempty"`
	Title     *string              `json:"title,omitempty"`
}

// GetUserProfileResponse defines model for GetUserProfileResponse.
type GetUserProfileResponse struct {
	AvatarUrl          *string                     `json:"avatarUrl,omitempty"`
	BirthDate          *openapi_types.Date         `json:"birthDate,omitempty"`
	CountryOfResidence *string                     `json:"countryOfResidence,omitempty"`
	Email              *openapi_types.Email        `json:"email,omitempty"`
	FavoriteCategories *[]string                   `json:"favoriteCategories,omitempty"`
	Id                 *openapi_types.UUID         `json:"id,omitempty"`
	IsBlocked          *bool                       `json:"isBlocked,omitempty"`
	Phone              *string                     `json:"phone,omitempty"`
	RegisteredAt       *time.Time                  `json:"registeredAt,omitempty"`
	Role               *GetUserProfileResponseRole `json:"role,omitempty"`
	Username           *string                     `json:"username,omitempty"`
}

// GetUserProfileResponseRole defines model for GetUserProfileResponse.Role.
type GetUserProfileResponseRole string

// HolidayResponse defines model for HolidayResponse.
type HolidayResponse struct {
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsNational  *bool               `json:"isNational,omitempty"`
	Name        *string             `json:"name,omitempty"`
}

// LoginUserRequest defines model for LoginUserRequest.
type LoginUserRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginUserResponse defines model for LoginUserResponse.
type LoginUserResponse struct {
	ChallengeId       *string              `json:"challengeId,omitempty"`
	Email             *openapi_types.Email `json:"email,omitempty"`
	Id                *openapi_types.UUID  `json:"id,omitempty"`
	RequiresTwoFactor *bool                `json:"requiresTwoFactor,omitempty"`
	Token             *string              `json:"token,omitempty"`
	Username          *string              `json:"username,omitempty"`
}

// ModerateReviewRequest defines model for ModerateReviewRequest.
type ModerateReviewRequest struct {
	Approved bool               `json:"approved"`
	Comment  *string            `json:"comment,omitempty"`
	ReviewId openapi_types.UUID `json:"reviewId"`
}

// ModerateReviewResponse defines model for ModerateReviewResponse.
type ModerateReviewResponse struct {
	Id                *openapi_types.UUID `json:"id,omitempty"`
	IsApproved        *bool               `json:"isApproved,omitempty"`
	IsModerated       *bool               `json:"isModerated,omitempty"`
	ModerationComment *string             `json:"moderationComment,omitempty"`
}

// ModerateUserRequest defines model for ModerateUserRequest.
type ModerateUserRequest struct {
	Block  bool               `json:"block"`
	Reason *string            `json:"reason,omitempty"`
	UserId openapi_types.UUID `json:"userId"`
}

// ModerateUserResponse defines model for ModerateUserResponse.
type ModerateUserResponse struct {
	BlockReason *string             `json:"blockReason,omitempty"`
	BlockedAt   *time.Time          `json:"blockedAt,omitempty"`
	IsBlocked   *bool               `json:"isBlocked,omitempty"`
	UserId      *openapi_types.UUID `json:"userId,omitempty"`
}

// PlaceResponse defines model for PlaceResponse.
type PlaceResponse struct {
	Address             *string                `json:"address,omitempty"`
	AvgRating           *float32               `json:"avgRating,omitempty"`
	AvgVisitDurationMin *int                   `json:"avgVisitDurationMin,omitempty"`
	Category            *string                `json:"category,omitempty"`
	CityId              *openapi_types.UUID    `json:"cityId,omitempty"`
	CityName            *string                `json:"cityName,omitempty"`
	ContactPhone        *string                `json:"contactPhone,omitempty"`
	Coordinates         *string                `json:"coordinates,omitempty"`
	Description         *string                `json:"description,omitempty"`
	DistrictId          *openapi_types.UUID    `json:"districtId,omitempty"`
	DistrictName        *string                `json:"districtName,omitempty"`
	Id                  *openapi_types.UUID    `json:"id,omitempty"`
	ImageUrl            *string                `json:"imageUrl,omitempty"`
	Name                *string                `json:"name,omitempty"`
	OpeningHours        *string                `json:"openingHours,omitempty"`
	PriceInfo           *string                `json:"priceInfo,omitempty"`
	Reviews             *[]ReviewBriefResponse `json:"reviews,omitempty"`
	ReviewsCount        *int                   `json:"reviewsCount,omitempty"`
	Website             *string                `json:"website,omitempty"`
}

// RegisterUserRequest defines model for RegisterUserRequest.
type RegisterUserRequest struct {
	BirthDate          *openapi_types.Date `json:"birthDate,omitempty"`
	CountryOfResidence *string             `json:"countryOfResidence,omitempty"`
	Email              openapi_types.Email `json:"email"`
	Password           string              `json:"password"`
	Phone              *string             `json:"phone,omitempty"`
	Username           string              `json:"username"`
}

// RegisterUserResponse defines model for RegisterUserResponse.
type RegisterUserResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Id       *openapi_types.UUID  `json:"id,omitempty"`
	Message  *string              `json:"message,omitempty"`
	Username *string              `json:"username,omitempty"`
}

// ReviewBriefResponse defines model for ReviewBriefResponse.
type ReviewBriefResponse struct {
	Comment    *string             `json:"comment,omitempty"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	IsApproved *bool               `json:"isApproved,omitempty"`
	Rating     *int                `json:"rating,omitempty"`
	Username   *string             `json:"username,omitempty"`
	VisitDate  *openapi_types.Date `json:"visitDate,omitempty"`
}

// StaticPageResponse defines model for StaticPageResponse.
type StaticPageResponse struct {
	Content         *string             `json:"content,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	ImageAlt        *string             `json:"imageAlt,omitempty"`
	ImageUrl        *string             `json:"imageUrl,omitempty"`
	IsPublished     *bool               `json:"isPublished,omitempty"`
	MetaDescription *string             `json:"metaDescription,omitempty"`
	PublishedAt     *time.Time          `json:"publishedAt,omitempty"`
	Slug            *string             `json:"slug,omitempty"`
	Title           *string             `json:"title,omitempty"`
	UpdatedAt       *time.Time          `json:"updatedAt,omitempty"`
}

// TransportNodeResponse defines model for TransportNodeResponse.
type TransportNodeResponse struct {
	Address     *string                        `json:"address,omitempty"`
	CityId      *openapi_types.UUID            `json:"cityId,omitempty"`
	Coordinates *Coordinates                   `json:"coordinates,omitempty"`
	Id          *openapi_types.UUID            `json:"id,omitempty"`
	ImageId     *openapi_types.UUID            `json:"imageId,omitempty"`
	Name        *string                        `json:"name,omitempty"`
	NodeType    *TransportNodeResponseNodeType `json:"nodeType,omitempty"`
}

// TransportNodeResponseNodeType defines model for TransportNodeResponse.NodeType.
type TransportNodeResponseNodeType string

// TripPlaceResponse defines model for TripPlaceResponse.
type TripPlaceResponse struct {
	ActualCost  *float32            `json:"actualCost,omitempty"`
	ArrivalTime *time.Time          `json:"arrivalTime,omitempty"`
	DayNumber   *int                `json:"dayNumber,omitempty"`
	DurationMin *int                `json:"durationMin,omitempty"`
	Notes       *string             `json:"notes,omitempty"`
	PlaceId     *openapi_types.UUID `json:"placeId,omitempty"`
	VisitStatus *string             `json:"visitStatus,omitempty"`
}

// TwoFactorResponse defines model for TwoFactorResponse.
type TwoFactorResponse struct {
	Token *string `json:"token,omitempty"`
}

// UpdateTripRequest defines model for UpdateTripRequest.
type UpdateTripRequest struct {
	Budget    *float32            `json:"budget,omitempty"`
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *string             `json:"status,omitempty"`
	Title     *string             `json:"title,omitempty"`
}

// UpdateUserProfileRequest defines model for UpdateUserProfileRequest.
type UpdateUserProfileRequest struct {
	AvatarUrl          *string             `json:"avatarUrl,omitempty"`
	BirthDate          *openapi_types.Date `json:"birthDate,omitempty"`
	CountryOfResidence *string             `json:"countryOfResidence,omitempty"`
	FavoriteCategories *[]string           `json:"favoriteCategories,omitempty"`
	Phone              *string             `json:"phone,omitempty"`
	Username           *string             `json:"username,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email        *openapi_types.Email `json:"email,omitempty"`
	Id           *openapi_types.UUID  `json:"id,omitempty"`
	IsBlocked    *bool                `json:"isBlocked,omitempty"`
	RegisteredAt *time.Time           `json:"registeredAt,omitempty"`
	Username     *string              `json:"username,omitempty"`
}

// UserReviewResponse defines model for UserReviewResponse.
type UserReviewResponse struct {
	Comment     *string             `json:"comment,omitempty"`
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsApproved  *bool               `json:"isApproved,omitempty"`
	IsModerated *bool               `json:"isModerated,omitempty"`
	PlaceId     *openapi_types.UUID `json:"placeId,omitempty"`
	PlaceName   *string             `json:"placeName,omitempty"`
	Rating      *int                `json:"rating,omitempty"`
	VisitDate   *openapi_types.Date `json:"visitDate,omitempty"`
}

// UserTripResponse defines model for UserTripResponse.
type UserTripResponse struct {
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *string             `json:"status,omitempty"`
	Title     *string             `json:"title,omitempty"`
}

// VerifyContactRequest defines model for VerifyContactRequest.
type VerifyContactRequest struct {
	Code    string             `json:"code"`
	Contact string             `json:"contact"`
	UserId  openapi_types.UUID `json:"userId"`
}

// VerifyTwoFactorRequest defines model for VerifyTwoFactorRequest.
type VerifyTwoFactorRequest struct {
	ChallengeId string `json:"challengeId"`
	Code        string `json:"code"`
}

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// SearchCitiesParams defines parameters for SearchCities.
type SearchCitiesParams struct {
	Query  *string `form:"query,omitempty" json:"query,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetDistrictsByCityParams defines parameters for GetDistrictsByCity.
type GetDistrictsByCityParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetTransportNodesByCityParams defines parameters for GetTransportNodesByCity.
type GetTransportNodesByCityParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetCountriesParams defines parameters for GetCountries.
type GetCountriesParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetCitiesByCountryParams defines parameters for GetCitiesByCountry.
type GetCitiesByCountryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetFavouritesParams defines parameters for GetFavourites.
type GetFavouritesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetHolidaysByDateParams defines parameters for GetHolidaysByDate.
type GetHolidaysByDateParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GetPendingReviewsParams defines parameters for GetPendingReviews.
type GetPendingReviewsParams struct {
	IsApproved *bool `form:"isApproved,omitempty" json:"isApproved,omitempty"`
	Limit      *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int  `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetPlacesParams defines parameters for GetPlaces.
type GetPlacesParams struct {
	CityId   *openapi_types.UUID    `form:"cityId,omitempty" json:"cityId,omitempty"`
	Category *string                `form:"category,omitempty" json:"category,omitempty"`
	SortBy   *GetPlacesParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	Limit    *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int                   `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPlacesParamsSortBy defines parameters for GetPlaces.
type GetPlacesParamsSortBy string

// GetReviewsByPlaceParams defines parameters for GetReviewsByPlace.
type GetReviewsByPlaceParams struct {
	OnlyApproved *bool `form:"onlyApproved,omitempty" json:"onlyApproved,omitempty"`
	Limit        *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset       *int  `form:"offset,omitempty" json:"offset,omitempty"`
}

// RemovePlaceFromTripParams defines parameters for RemovePlaceFromTrip.
type RemovePlaceFromTripParams struct {
	PlaceId openapi_types.UUID `form:"placeId" json:"placeId"`
}

// GetUserReviewsParams defines parameters for GetUserReviews.
type GetUserReviewsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GenerateReportJSONRequestBody defines body for GenerateReport for application/json ContentType.
type GenerateReportJSONRequestBody = GenerateReportRequest

// EnableTwoFactorJSONRequestBody defines body for EnableTwoFactor for application/json ContentType.
type EnableTwoFactorJSONRequestBody = EnableTwoFactorRequest

// VerifyTwoFactorJSONRequestBody defines body for VerifyTwoFactor for application/json ContentType.
type VerifyTwoFactorJSONRequestBody = VerifyTwoFactorRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginUserRequest

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = UpdateUserProfileRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterUserRequest

// VerifyContactJSONRequestBody defines body for VerifyContact for application/json ContentType.
type VerifyContactJSONRequestBody = VerifyContactRequest

// RemoveFavouriteJSONRequestBody defines body for RemoveFavourite for application/json ContentType.
type RemoveFavouriteJSONRequestBody = FavouriteRequest

// AddFavouriteJSONRequestBody defines body for AddFavourite for application/json ContentType.
type AddFavouriteJSONRequestBody = FavouriteRequest

// ModerateReviewJSONRequestBody defines body for ModerateReview for application/json ContentType.
type ModerateReviewJSONRequestBody = ModerateReviewRequest

// ModerateUserJSONRequestBody defines body for ModerateUser for application/json ContentType.
type ModerateUserJSONRequestBody = ModerateUserRequest

// CreateReviewJSONRequestBody defines body for CreateReview for application/json ContentType.
type CreateReviewJSONRequestBody = CreateReviewRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = UpdateTripRequest

// AddPlaceToTripJSONRequestBody defines body for AddPlaceToTrip for application/json ContentType.
type AddPlaceToTripJSONRequestBody = AddPlaceToTripRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GenerateReport Request analytics report generation (Async)
	// (POST /api/v1/analytics/reports)
	GenerateReport(ctx echo.Context) error
	// StreamReportStatus Stream report generation status and result (SSE)
	// (GET /api/v1/analytics/reports/{reportId}/stream)
	StreamReportStatus(ctx echo.Context, reportId openapi_types.UUID) error
	// EnableTwoFactor Enable TOTP 2FA for current user
	// (POST /api/v1/auth/2fa/enable)
	EnableTwoFactor(ctx echo.Context) error
	// VerifyTwoFactor Verify 2FA code during login
	// (POST /api/v1/auth/2fa/verify)
	VerifyTwoFactor(ctx echo.Context) error
	// Login Login with username/password
	// (POST /api/v1/auth/login)
	Login(ctx echo.Context) error
	// Logout Logout (invalidate token)
	// (POST /api/v1/auth/logout)
	Logout(ctx echo.Context) error
	// GetUserProfile Get current user profile
	// (GET /api/v1/auth/profile)
	GetUserProfile(ctx echo.Context) error
	// UpdateUserProfile Partial update of user profile
	// (PATCH /api/v1/auth/profile)
	UpdateUserProfile(ctx echo.Context) error
	// RegisterUser Register new user
	// (POST /api/v1/auth/register)
	RegisterUser(ctx echo.Context) error
	// VerifyContact Verify email or phone with code
	// (POST /api/v1/auth/verify)
	VerifyContact(ctx echo.Context) error
	// SearchCities Search cities by name
	// (GET /api/v1/cities)
	SearchCities(ctx echo.Context, params SearchCitiesParams) error
	// GetDistrictsByCity Get districts of a city
	// (GET /api/v1/cities/{cityId}/districts)
	GetDistrictsByCity(ctx echo.Context, cityId openapi_types.UUID, params GetDistrictsByCityParams) error
	// GetTransportNodesByCity Get transport nodes in a city
	// (GET /api/v1/cities/{cityId}/transports)
	GetTransportNodesByCity(ctx echo.Context, cityId openapi_types.UUID, params GetTransportNodesByCityParams) error
	// GetCity Get city by ID
	// (GET /api/v1/cities/{id})
	GetCity(ctx echo.Context, id openapi_types.UUID) error
	// GetCountries List countries with pagination and search
	// (GET /api/v1/countries)
	GetCountries(ctx echo.Context, params GetCountriesParams) error
	// GetCitiesByCountry List cities by country
	// (GET /api/v1/countries/{countryId}/cities)
	GetCitiesByCountry(ctx echo.Context, countryId openapi_types.UUID, params GetCitiesByCountryParams) error
	// GetCountry Get detailed country information including holidays
	// (GET /api/v1/countries/{id})
	GetCountry(ctx echo.Context, id openapi_types.UUID) error
	// RemoveFavourite Remove a place from favourites
	// (DELETE /api/v1/favourites)
	RemoveFavourite(ctx echo.Context) error
	// GetFavourites Get user's favourite places
	// (GET /api/v1/favourites)
	GetFavourites(ctx echo.Context, params GetFavouritesParams) error
	// AddFavourite Add a place to favourites
	// (POST /api/v1/favourites)
	AddFavourite(ctx echo.Context) error
	// GetStaticPage Get static page by ID (any status)
	// (GET /api/v1/files/{id})
	GetStaticPage(ctx echo.Context, id openapi_types.UUID) error
	// GetHolidaysByDate Get holidays by date
	// (GET /api/v1/holidays)
	GetHolidaysByDate(ctx echo.Context, params GetHolidaysByDateParams) error
	// GetPendingReviews Get reviews for moderation (moderator/analyst)
	// (GET /api/v1/moderation/reviews)
	GetPendingReviews(ctx echo.Context, params GetPendingReviewsParams) error
	// ModerateReview Moderate a review (moderators only)
	// (POST /api/v1/moderation/reviews)
	ModerateReview(ctx echo.Context) error
	// GetUsers Get list of users (moderator only)
	// (GET /api/v1/moderation/users)
	GetUsers(ctx echo.Context, params GetUsersParams) error
	// ModerateUser Block/unblock user (moderator only)
	// (POST /api/v1/moderation/users)
	ModerateUser(ctx echo.Context) error
	// GetPlaces List places (optionally filtered by city and/or category)
	// (GET /api/v1/places)
	GetPlaces(ctx echo.Context, params GetPlacesParams) error
	// GetPlace Get detailed place information with reviews
	// (GET /api/v1/places/{id})
	GetPlace(ctx echo.Context, id openapi_types.UUID) error
	// GetReviewsByPlace Get reviews for a place
	// (GET /api/v1/places/{placeId}/reviews)
	GetReviewsByPlace(ctx echo.Context, placeId openapi_types.UUID, params GetReviewsByPlaceParams) error
	// CreateReview Create a review for a place
	// (POST /api/v1/places/{placeId}/reviews)
	CreateReview(ctx echo.Context, placeId openapi_types.UUID) error
	// DeleteReview Delete a review (owner or moderator)
	// (DELETE /api/v1/reviews/{reviewId})
	DeleteReview(ctx echo.Context, reviewId openapi_types.UUID) error
	// GetUserTrips Get current user's trips
	// (GET /api/v1/trips)
	GetUserTrips(ctx echo.Context) error
	// CreateTrip Create a new trip
	// (POST /api/v1/trips)
	CreateTrip(ctx echo.Context) error
	// DeleteTrip Delete trip
	// (DELETE /api/v1/trips/{tripId})
	DeleteTrip(ctx echo.Context, tripId openapi_types.UUID) error
	// GetTrip Get trip by ID
	// (GET /api/v1/trips/{tripId})
	GetTrip(ctx echo.Context, tripId openapi_types.UUID) error
	// UpdateTrip Partial update of a trip
	// (PATCH /api/v1/trips/{tripId})
	UpdateTrip(ctx echo.Context, tripId openapi_types.UUID) error
	// RemovePlaceFromTrip Remove a place from trip
	// (DELETE /api/v1/trips/{tripId}/places)
	RemovePlaceFromTrip(ctx echo.Context, tripId openapi_types.UUID, params RemovePlaceFromTripParams) error
	// AddPlaceToTrip Add a place to trip
	// (POST /api/v1/trips/{tripId}/places)
	AddPlaceToTrip(ctx echo.Context, tripId openapi_types.UUID) error
	// GetUserReviews Get current user's reviews
	// (GET /api/v1/users/me/reviews)
	GetUserReviews(ctx echo.Context, params GetUserReviewsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GenerateReport converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateReport(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GenerateReport(ctx)
	return err
}

// StreamReportStatus converts echo context to params.
func (w *ServerInterfaceWrapper) StreamReportStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reportId" -------------
	var reportId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reportId", ctx.Param("reportId"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reportId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StreamReportStatus(ctx, reportId)
	return err
}

// EnableTwoFactor converts echo context to params.
func (w *ServerInterfaceWrapper) EnableTwoFactor(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnableTwoFactor(ctx)
	return err
}

// VerifyTwoFactor converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyTwoFactor(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyTwoFactor(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx)
	return err
}

// UpdateUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserProfile(ctx)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// VerifyContact converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyContact(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyContact(ctx)
	return err
}

// SearchCities converts echo context to params.
func (w *ServerInterfaceWrapper) SearchCities(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCitiesParams
	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", ctx.QueryParams(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchCities(ctx, params)
	return err
}

// GetDistrictsByCity converts echo context to params.
func (w *ServerInterfaceWrapper) GetDistrictsByCity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cityId" -------------
	var cityId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cityId", ctx.Param("cityId"), &cityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cityId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDistrictsByCityParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDistrictsByCity(ctx, cityId, params)
	return err
}

// GetTransportNodesByCity converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransportNodesByCity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cityId" -------------
	var cityId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cityId", ctx.Param("cityId"), &cityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cityId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransportNodesByCityParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransportNodesByCity(ctx, cityId, params)
	return err
}

// GetCity converts echo context to params.
func (w *ServerInterfaceWrapper) GetCity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCity(ctx, id)
	return err
}

// GetCountries converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountries(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCountriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountries(ctx, params)
	return err
}

// GetCitiesByCountry converts echo context to params.
func (w *ServerInterfaceWrapper) GetCitiesByCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "countryId" -------------
	var countryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "countryId", ctx.Param("countryId"), &countryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter countryId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCitiesByCountryParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCitiesByCountry(ctx, countryId, params)
	return err
}

// GetCountry converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountry(ctx, id)
	return err
}

// RemoveFavourite converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveFavourite(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveFavourite(ctx)
	return err
}

// GetFavourites converts echo context to params.
func (w *ServerInterfaceWrapper) GetFavourites(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFavouritesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFavourites(ctx, params)
	return err
}

// AddFavourite converts echo context to params.
func (w *ServerInterfaceWrapper) AddFavourite(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddFavourite(ctx)
	return err
}

// GetStaticPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetStaticPage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStaticPage(ctx, id)
	return err
}

// GetHolidaysByDate converts echo context to params.
func (w *ServerInterfaceWrapper) GetHolidaysByDate(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHolidaysByDateParams
	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", ctx.QueryParams(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHolidaysByDate(ctx, params)
	return err
}

// GetPendingReviews converts echo context to params.
func (w *ServerInterfaceWrapper) GetPendingReviews(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPendingReviewsParams
	// ------------- Optional query parameter "isApproved" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isApproved", ctx.QueryParams(), &params.IsApproved, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter isApproved: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPendingReviews(ctx, params)
	return err
}

// ModerateReview converts echo context to params.
func (w *ServerInterfaceWrapper) ModerateReview(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ModerateReview(ctx)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx, params)
	return err
}

// ModerateUser converts echo context to params.
func (w *ServerInterfaceWrapper) ModerateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ModerateUser(ctx)
	return err
}

// GetPlaces converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlaces(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlacesParams
	// ------------- Optional query parameter "cityId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cityId", ctx.QueryParams(), &params.CityId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cityId: %s", err))
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", ctx.QueryParams(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortBy", ctx.QueryParams(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortBy: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlaces(ctx, params)
	return err
}

// GetPlace converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlace(ctx, id)
	return err
}

// GetReviewsByPlace converts echo context to params.
func (w *ServerInterfaceWrapper) GetReviewsByPlace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "placeId" -------------
	var placeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "placeId", ctx.Param("placeId"), &placeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter placeId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewsByPlaceParams
	// ------------- Optional query parameter "onlyApproved" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "onlyApproved", ctx.QueryParams(), &params.OnlyApproved, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter onlyApproved: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReviewsByPlace(ctx, placeId, params)
	return err
}

// CreateReview converts echo context to params.
func (w *ServerInterfaceWrapper) CreateReview(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "placeId" -------------
	var placeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "placeId", ctx.Param("placeId"), &placeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter placeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateReview(ctx, placeId)
	return err
}

// DeleteReview converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteReview(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", ctx.Param("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reviewId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteReview(ctx, reviewId)
	return err
}

// GetUserTrips converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserTrips(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserTrips(ctx)
	return err
}

// CreateTrip converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTrip(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTrip(ctx)
	return err
}

// DeleteTrip converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTrip(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", ctx.Param("tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tripId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTrip(ctx, tripId)
	return err
}

// GetTrip converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrip(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", ctx.Param("tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tripId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTrip(ctx, tripId)
	return err
}

// UpdateTrip converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTrip(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", ctx.Param("tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tripId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTrip(ctx, tripId)
	return err
}

// RemovePlaceFromTrip converts echo context to params.
func (w *ServerInterfaceWrapper) RemovePlaceFromTrip(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", ctx.Param("tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tripId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RemovePlaceFromTripParams
	// ------------- Required query parameter "placeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "placeId", ctx.QueryParams(), &params.PlaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter placeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemovePlaceFromTrip(ctx, tripId, params)
	return err
}

// AddPlaceToTrip converts echo context to params.
func (w *ServerInterfaceWrapper) AddPlaceToTrip(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", ctx.Param("tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tripId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddPlaceToTrip(ctx, tripId)
	return err
}

// GetUserReviews converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserReviews(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserReviewsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserReviews(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser, options.OperationMiddlewares["registerUser"]...)
	router.POST(options.BaseURL+"/api/v1/auth/verify", wrapper.VerifyContact, options.OperationMiddlewares["verifyContact"]...)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.POST(options.BaseURL+"/api/v1/auth/2fa/enable", wrapper.EnableTwoFactor, options.OperationMiddlewares["enableTwoFactor"]...)
	router.POST(options.BaseURL+"/api/v1/auth/2fa/verify", wrapper.VerifyTwoFactor, options.OperationMiddlewares["verifyTwoFactor"]...)
	router.GET(options.BaseURL+"/api/v1/auth/profile", wrapper.GetUserProfile, options.OperationMiddlewares["getUserProfile"]...)
	router.PATCH(options.BaseURL+"/api/v1/auth/profile", wrapper.UpdateUserProfile, options.OperationMiddlewares["updateUserProfile"]...)
	router.GET(options.BaseURL+"/api/v1/countries", wrapper.GetCountries, options.OperationMiddlewares["getCountries"]...)
	router.GET(options.BaseURL+"/api/v1/countries/:id", wrapper.GetCountry, options.OperationMiddlewares["getCountry"]...)
	router.GET(options.BaseURL+"/api/v1/countries/:countryId/cities", wrapper.GetCitiesByCountry, options.OperationMiddlewares["getCitiesByCountry"]...)
	router.GET(options.BaseURL+"/api/v1/cities", wrapper.SearchCities, options.OperationMiddlewares["searchCities"]...)
	router.GET(options.BaseURL+"/api/v1/cities/:id", wrapper.GetCity, options.OperationMiddlewares["getCity"]...)
	router.GET(options.BaseURL+"/api/v1/cities/:cityId/districts", wrapper.GetDistrictsByCity, options.OperationMiddlewares["getDistrictsByCity"]...)
	router.GET(options.BaseURL+"/api/v1/cities/:cityId/transports", wrapper.GetTransportNodesByCity, options.OperationMiddlewares["getTransportNodesByCity"]...)
	router.GET(options.BaseURL+"/api/v1/places", wrapper.GetPlaces, options.OperationMiddlewares["getPlaces"]...)
	router.GET(options.BaseURL+"/api/v1/places/:id", wrapper.GetPlace, options.OperationMiddlewares["getPlace"]...)
	router.GET(options.BaseURL+"/api/v1/trips", wrapper.GetUserTrips, options.OperationMiddlewares["getUserTrips"]...)
	router.POST(options.BaseURL+"/api/v1/trips", wrapper.CreateTrip, options.OperationMiddlewares["createTrip"]...)
	router.DELETE(options.BaseURL+"/api/v1/trips/:tripId", wrapper.DeleteTrip, options.OperationMiddlewares["deleteTrip"]...)
	router.GET(options.BaseURL+"/api/v1/trips/:tripId", wrapper.GetTrip, options.OperationMiddlewares["getTrip"]...)
	router.PATCH(options.BaseURL+"/api/v1/trips/:tripId", wrapper.UpdateTrip, options.OperationMiddlewares["updateTrip"]...)
	router.DELETE(options.BaseURL+"/api/v1/trips/:tripId/places", wrapper.RemovePlaceFromTrip, options.OperationMiddlewares["removePlaceFromTrip"]...)
	router.POST(options.BaseURL+"/api/v1/trips/:tripId/places", wrapper.AddPlaceToTrip, options.OperationMiddlewares["addPlaceToTrip"]...)
	router.GET(options.BaseURL+"/api/v1/holidays", wrapper.GetHolidaysByDate, options.OperationMiddlewares["getHolidaysByDate"]...)
	router.GET(options.BaseURL+"/api/v1/files/:id", wrapper.GetStaticPage, options.OperationMiddlewares["getStaticPage"]...)
	router.GET(options.BaseURL+"/api/v1/places/:placeId/reviews", wrapper.GetReviewsByPlace, options.OperationMiddlewares["getReviewsByPlace"]...)
	router.POST(options.BaseURL+"/api/v1/places/:placeId/reviews", wrapper.CreateReview, options.OperationMiddlewares["createReview"]...)
	router.GET(options.BaseURL+"/api/v1/users/me/reviews", wrapper.GetUserReviews, options.OperationMiddlewares["getUserReviews"]...)
	router.DELETE(options.BaseURL+"/api/v1/reviews/:reviewId", wrapper.DeleteReview, options.OperationMiddlewares["deleteReview"]...)
	router.GET(options.BaseURL+"/api/v1/moderation/users", wrapper.GetUsers, options.OperationMiddlewares["getUsers"]...)
	router.POST(options.BaseURL+"/api/v1/moderation/users", wrapper.ModerateUser, options.OperationMiddlewares["moderateUser"]...)
	router.GET(options.BaseURL+"/api/v1/moderation/reviews", wrapper.GetPendingReviews, options.OperationMiddlewares["getPendingReviews"]...)
	router.POST(options.BaseURL+"/api/v1/moderation/reviews", wrapper.ModerateReview, options.OperationMiddlewares["moderateReview"]...)
	router.POST(options.BaseURL+"/api/v1/analytics/reports", wrapper.GenerateReport, options.OperationMiddlewares["generateReport"]...)
	router.GET(options.BaseURL+"/api/v1/analytics/reports/:reportId/stream", wrapper.StreamReportStatus, options.OperationMiddlewares["streamReportStatus"]...)
	router.DELETE(options.BaseURL+"/api/v1/favourites", wrapper.RemoveFavourite, options.OperationMiddlewares["removeFavourite"]...)
	router.GET(options.BaseURL+"/api/v1/favourites", wrapper.GetFavourites, options.OperationMiddlewares["getFavourites"]...)
	router.POST(options.BaseURL+"/api/v1/favourites", wrapper.AddFavourite, options.OperationMiddlewares["addFavourite"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F19bxvHmf8qg70ClS+kSMkviVUcUlmOUxepa0hyCzRUrRF3SE2z3GVnZ+UwAgFLapornHMuRQ+XPw7t",
	"FXcfQFakmrYs6SvMfoX7JId52fdZvomUKIX5Ixa5y9nZZ37P+/PMbBtVp9F0bGRT11jYNghym47tIvHh",
	"gUM2sGkim3+oOjZFNuV/wmbTwlVIsWOXfuc64rJb3UQNyP/6EUE1Y8H4p1I0ckledUsfEeKQZfUMo91u",
	"FwwTuVWCm3wwYyF6JCiCh7br1Wq4ipFNQRORBnZd7Niu0S4Yjxz6wPFs8+JmtoxcxyNVBGyHgpp4drtg",
	"PLGhRzcdgr9AFziX+FMFobaghU3gECBoZNcBdT5DtsF/qQblz1w0zccWrKJVZ5Xg5jL6vYdcOVXTxHxo",
	"aD0mThMRijkAatByUcFoxr7aNiAheAtaq7iB+MeaQxqQGguGCSkqUv5twWjAzz9Bdp1uGgs3ywWjCSlF",
	"hM/7t5WKuX2rXeT/zAf/rMp/FhL/zFQqs5WK+d6ND3/z4Y+MgkFbTWQsGC4l2K5zwpuw9chrbCDCZ9HA",
	"Nm54DWNhLrwT2xTVERG3ekSswi+wnbi5rLvZdqh80dhLzJXLydf49LeVyuflcrFS+Xzuwdo/ayfY5JR+",
	"aCaI5HnYTNHnTnLgcvEuLNYWiw/Wtj9oF+Mfbw3ycW6+rZlUu2AQ9HsPE47VT8MZxom5Fv7I2fgdqlL+",
	"JkuYtkI0DoaWquMQE9tQ0bQb6Jdit6YBn1iN+WFWA0/UQhQM3IB19IRYfFboc9hoWvz6JqVNd6FUUt/M",
	"Vp1GSdw5+7tmPTnf2ykiiJ9+uFAqJanxnv7p7hJsYgrF49XVDcexELQFD0DJ3EkWGJwDnKZnwWAFQ9pj",
	"m965Zeh4j4uPLxw7/ezbqUcvFn8Di1+Unr5XqRTLxbvad2zrcJwE4wAwtiBNCjvH27CUpJOy5G65EAmW",
	"4t1ItNiSr9oFw7LrPQaZ+yAxiviYGibFwnxicmQt4zqeTcmwvAsJgjF8RC9SjbBzToRUPUKQXW0luWD5",
	"yb0k1ueyAFjbvtmeMnpPRregXfdgfRTcPCqhsOnYaMkxUZIg770/F/7XdfErlfc+5CbCXGGu3B6F2NFK",
	"CoIgRctoC6Nnw5lJVafRUHbguVXXpSKIm05ScIVi6nahh8G1hV1M70OatRB7LG3WOOxtxagJFkKSx5+/",
	"1nNxhzRrRra6VTEbc5FeqjU9cVLTXWw2ibMlnaqshYLdXzgmIpxy+hsmErY5UBzeGdvwzDqiOU5NpLCR",
	"bY7ttfQe01Cs4FJI6BgnSjG10ips/vbtAeeZEj9y0PjkI3qv9VjyoWRPtOYXvM6TJiPGDReXQuq5PXyR",
	"PmA9MthlsHQf86tVOqwWw7T1cMIWdRow6OZHTNpqjcQn0CH7IxtuWGj1mfMAVqlDhrXBzezsMrIg35Fw",
	"UZUg2uv9Fou/mS++/y855rPnIjLRQUA1wfBtC5Jsa/0synD6C1Y/85rcAxQfMUWNrPWQIXG5eLeYQ+IG",
	"/PyhHGQ+Mn4gIbDFrzq0CT26+YTgjCRPPkXd2JdbpIVsImg/GE1MRCG2RhJ2RnwaozZy5KA6TDyAW45H",
	"MPenhmHRqxMk1738x8gWPsgyajqEDkcBbq88IE5jTEYMH2nVGdPgwZDbBrK57/GpIfJcBaPqbnGCdQnh",
	"weIXeSEr3MA04bhJPujuuxGxBKvi+2g6MhREnopFdA0pjp/CKsVbmLb40wluPuWGHnYprrqpSd/OTvpp",
	"njxIhCSiyYRE0uOHXkpupSrjwpNmTUwtuGke6rrlobiIgVvIWsXNEcRI2jlCZDx5ng3k0hUE3Qw7DpXq",
	"kQs9cf6mnNaj0SBtDPmsfKF4exihWDeb2rXedCxswlbSJO+mUn4mfxBVqcQNcSEU0pb4NDM3zcwNKIgJ",
	"snAdj0T+uLCGaGs0YlikCuCytPgaQencWET7NFA8gijVqBIUyo3oV0TytRP1dnohOa8TktOg9seIPnER",
	"eUycGrbQsDbNFqSQKOE+KpG9gQndHOPaKLfsl7Vl5GIT2dVRSHXUgNhKTFh+U+i+cj+tVNy1934a/FGp",
	"zAZ/6iMBcMshmKIlSFHdITg/tjcE1uJ2xRUwK9x7llP9LC8xLbTs+WlCUB27FJFLrxwgjpUIuXguIvzR",
	"Mj3v8L+hDa2WS1PBlfm+I0J8yLFlGtJ27ODRu3FF7q55NMR9BCWR+/b950ey4J84dWxzDTNkxBq67jOH",
	"mKm5vT8/8IqMEtbpjI4YtxBNdq07IYaLP25Cy0J2ENO6Enpq0rhArZsbJtX0zCC7OXplh2Q8qly8O/u0",
	"UilehjANirLOUzkJuxZ+6SvvhsqUETHJiU4+hVMsRGRZ64PuQ/HztasBVDYIduylUaGmG+iH1ykb3GDM",
	"qWPUxV9vD4H2q1OIIKmx1pPSwwVF+ODLoyLqhrT0L7t4t7vHMZErn1nbZKBkQJVhmgS57ggWFG7Vl8PK",
	"4UzYDG7VfyVqhJMNhdm4ZVW6wa1RpBQmsUgP09aoMiaOTWGVPu7tFcfCy7f7qh3MH6qoBroZ462C7suL",
	"yMiYqohz4rLxal4jWuhp9qdHymZ+CKI6TWRju/4zxyPuCIZrElxFD+2aM4KxpOnaf7Bcmq73CEa1AXKK",
	"6ikiAa4Xxc/QhospGl0cWKe8llU07hwm4DS2nOezd4m4NLAdfLwzXL7z/JHYCwjjBFTtGs5JYnAoO+qH",
	"GYNpINfNJuIHT2aNObaiE5DTrsUrFbEYpilxZJi6jP7GFQoprj6GdTQ0ZMPtdFKBm2tigS5adASC57Kr",
	"OB97GxZ2N3MDcYjC+/nprCFeuBk88JIlkGt59V6cKWPyefH40RRSFAyvaV66RNaJgFUCbbfpEPrIMS8/",
	"vnO9Wh6nFe7D9SgO48/ajonS7SUQE45s0UcCsS0bSUQDzIbnxj6Jm3pWPzzt293MFpYNyE9V6kFryXH1",
	"1YETucVbz23dflhbuSlrbmUk5XxajJ2zzXNkKWvd5J4IZTfdN2O6EUIcD4my0aFKD6ZVo5dfzzmBYbks",
	"3qYxtpEWxU5MNesFoGa67dg13nZsIi1FMalHo3GDrsa+apzTztE5Nd1H64dlPv4KEVxrLclSlJHtNXSn",
	"S36Sk+tOu1tFzIjSUVej5C945y6bD8k1Ou+OUCMtWT/f/lIpWsSnlksGuSmVRzBtrVQ3UUO+1T0ECSKL",
	"Hp/AtrEhPj0IVvznv1411CEAQleJq9FsuCsjTxjAqu4jhj9pCRkfI+djD5sIrCLYyFRAGYuPHwJ2yI79",
	"bwD7nh2xU/a9/5zt+39gHf8rduTvsLf8O3YK/B12xi+xA3bqf8VOWIe9ZfuAdQA7Y8dsn3/jP2en7MD/",
	"U3DtzN/zd9mR/698JH+XHbAOezNbsdnf2Ck7ZIfsyH/O/sE67IDtsyN/F/jP2RH7nnX43WIef2Qd/2UB",
	"zD9YLAB/L5zBMTsSMzjiDz9lR+w1O+SPZO9YpwDYqb/LXvsvxLDv+Aw7QExwnx2zjr/Lp+fvzVZsIxRM",
	"EZ0WHz80CsYWIq6k0NxsebYc1OvAJjYWjJuzc7NlkdKnm2IRS7CJS1tzJdEsRXHVLcldZGTTiQrVJQnP",
	"/pPtC/rsiHnzl2f7/g7rsBP/S0HHE3bi7/kv5bqcCFIpeqReJrVQ/O39r/xv/V21PAfslL1mB+L3f1LP",
	"+sSRh1sEi68I3uHkYifse7YvvmL7/q6Y4/6sISggo3acA1MbKBmSI5BL7zlma2Snaeh3aWonGZASD4kv",
	"YsefzJfns0SXo4C6HJS/vtCfiHPtJoImkpVYAXGyAzxZ/gRQB1Q3UfUzIHUjcAhwKUGwAQhyPYu6AcvC",
	"ZEYvFySlufmb6NbtO+8X0Qd3N4pz8+bNIrx1+07x1vydO3O35t6/VS6XS/IZ3TN//VRAcdLdKs/lET4k",
	"YilxOor40c3eP4pOnYnLO2Ph06Sk+3StvVYwXK/RgKQlFkYsLAhpA0hmqWYW3ZZdvcFfCdZdLnYXg7uN",
	"Nf60fAJvyz8emu2AjAvbhgoiJhd4BZEtRIoryKbgoy3+cmBmZeWjGwDZZtPBNgU1hwDIZ7JJHNvxNDOd",
	"rdjLiHrEdgEMoOHUABLDLYB1E1K4ALYryriqGAugwnVdFYnjXypGQX6uE+SKq7fL7XVQsWuOZTnPkAk2",
	"WjmD8CWxEEWmHMMjlvw+jrTZqrtVMdrrUvwlWXpFTFZyiYpOc3wR2EBU8Man2wbmZOKSzwjSM0ZAXSPN",
	"lHFGmBgzZi0jKcopcUXR57QklqsYwSV6kyRiBlqI2dnZitGu2IL2/RZFlD/g/7vH/7fE//dRNws5o+E1",
	"iFYvdVGCgP/iVu9fhKdCDSQ5VgLRq5HsXDpD21RyWTJyH+LDo5ul+RosIbFlZhcV/mf2lh37L/2vlFJd",
	"/eXqY26q5GpduX1mUajqQ/8Fv0/tXAmeLD/MqtjUpp1j0rE5+7X2pWTL45tF/glanMRyccwCIErUStoC",
	"bnzLVY9RdkioD4JDOf0IAlxNyB2lKFBt9SHu+AB6yG0JR6kL5P4mTWxuDfrfSKtRgEnC7oCbfwfCiH7H",
	"LfoD/0thaCs70H/B/+aWIfj5r1ezcEu5aWOCW44zeMFw6wtoK16VK+WaZwGxMupREei4gyZgEuJAvp1Y",
	"Dg5FYHpcMAPLqWO7NwbkbfnL/+/SoWInwu7nThp3CJ77exIK3Bc69r9mrwVG9sWtwrU748A4Fg4CdzD2",
	"lNu2L9B07L/8CRCulRBbSqb533IPhJ2yNyG2MvIs5vdm0fSJeuVxYCizD8AFoyfbfq9Bj7gJBHMAMw3Y",
	"AmqKnKQ3UsiRtz/DdBMEmYxSWDTeD3Icj3aBznfsRPjDx6zDDmOgESB56+8Jr/0NR3TR32Wn7C2HWS6k",
	"tMvNJ5Ah+i2NkR2yldXinFFHJuC/Hb+UlpMEM1geuggpkoct3uhN4KZMTud6DuzPGgYRXHXKGZUTMU7r",
	"I+mr7+sZWhJbMaC4se91SG7BZIyRCXI2e9IdeekiAhQBATeYL2CpP0Y0oYCD52dXWtjd1U3Nkv6VvRIr",
	"cMBJHXCLXIe3clGOhLI9lGvlvwgCUlLoxtb+mwJgJ/zqaxFSec72hSjmK/kNYKcy1iIGFqNklzVTJTEm",
	"yZpbjXHBEnYAcMni2XB9BbTK2dX8leR47hvILdHHj8HHkFAMLSDre4FT64HEtMwJUutdxPrfhdQJzDqF",
	"1u4yQyj/U383iqYmTUnxu0MRrpXx2UMZbeW/PGH7QNQ8AA5r1pEi7Zgd+X9gp+wki9t4Z9OYIKtr4OsL",
	"rXNjmkIPQajS94WETamo6vKpRAi+mBOJs5zRTgbn5MsBGz3r05fp7cdkICYVZhds9TJvuaNzwk4Fpl8r",
	"NnjHTV3pbe/l+TtLYf5qfN5OKj3ZvyxNLZQADDKBG7OgcgVecLK0yEdpvRRJbYcAUbclbU9xd7cFruIg",
	"I6e3g77j1g2XJt+LxVD+51kgkA5VqkFYmIAdCJnCDSeZQmKd7DqtIEiqm0vyufqA5O89RFpRRDL4GK3R",
	"OQuC9I+Rxx0UErHBGvQsKmvE44cgdK+zyHuAU6u5KOcJ8SE1p2H3Eefsjuq+Or8TRyAkygPnsi3fWcnz",
	"C254cf9YgSqJUrnu6hrYaAHVUhtgUyFCg87StmwWaZeCnRDcwQx3f4edsY6/w2EKhEh5I1Jyp+wA+Hsi",
	"Zfc6aaDH0K41yoPzvtx7rSV5fkXvwLrqeLkSYfUpi+SwSOagt8HZ5BPsUm49RmAeLqiecI7CwfjIkHNZ",
	"a0DeokF72LmYS3pDJ+LLU/+5v8tdIP9LzmavRczqAMywff/fBHepW/wXBRmReivY8FjG0v3dWXY2e0Mo",
	"lYgdj7TsmGhtm/LkD4wn9Y2NwzNmyAnAFmejjYA9U0MCbA/GpNhsDxqrEtYZZ5pXQelJh51w49t/zt5F",
	"xScJZXekTDsVz+pIZzGIZnFF6e8Knt3TsmHfbIevTXb5XDGRpL2VBSS/DoIT6UaAQg44bnk9vN8LdqKT",
	"patj0FsV7ATKAPg7Ij8h8xUSeuyIvVF5i1PxE+7XvVPwS/gQ/ks91sIp9uVDTLSUzBnSFRbzCB2fi3Ei",
	"UkcgDS+HIxSmciv8enhROrpNWMe2jHpA2wQh6UKUh2PpgV7aDo9ia/d0intiPyZStT7Gmxh3+C/y+CNP",
	"xmJh4sjp9mflhKfMTQ2dH7B/HvKVcs/Pp1AkF4befDXEY1+KZbwmTcRd7KgQS4PLBM2ZiioeqrrnThcF",
	"M7VnBrFn0qI/i8H7wppBZoCXWALxnA5wemBsS7JzlYDtquWZ2K6D8HS1nqqhFpynq84FtpDsy0kh9X9E",
	"tDtMurxTxfHCen4daQVZXc9es1cKl0GoKZtFzksOg3XV07aeyFX63/q7/o4oEApj7LrMTcPZQuEZwWOK",
	"j2fOIO4rNn5LV9vdEL1/w1c1jq1GUU4NQCBWA9SI0wAxrES4ehB9udYuDG1KJEAjYikByAbAjk7APYhP",
	"+qqb0Beif7scITaQAg7hAtQ5ZhdTQOG5iPzYzT49F7I56b6/CA2cyDXHxN5BN/wOLPQywF00zcmUYnNZ",
	"Si2aZiCOLjABfA+agAQznzz5uWiaofCkTh+iM66TsTWU6Rh0P0XtVcJ8jJmJHf+P/l4Q/fK/7Rr7EiHp",
	"Y/8leyViFonWKn18Otp9cWpO9glzzYaVuppecRf3/hEIHjsCY9KNDSviZWAG2i3VhXAjYTvKZyZQGj/B",
	"d1itn/ZRTtlBQZX1yjJw/xv/T/xvafqdsP1UlEH6R4cSmFpQqvPW3Hut+7LDvA8bQPWi94HNkW0qcCGa",
	"fdAzlPN1e7j4WVQFlzikFHm64ig6NacU28N9AIc57Jz1X4R9we9koD/oP2WdWcD+V1a0cmEI1qOdN9YX",
	"Kva66N5eB//3/C+AnYr2Xo6pl6LA+EgzHJgRQtTfE5eORTuNiOLeKIB1jhY5lr/H/sF/L0Nkr4Qzo4ou",
	"db1sHyP6GNncg1tWlOgLrrFdRLRWpWpNT+8eMo1ADX02wEB2sEI1aMqlBRHgjUnsa+U8HEy55pDYdMFM",
	"eMpmSZ2xmShCNxvY7mZR/zXggsCeliVzgoHfirT5SXAl5OmfdLFREk3zPaMFoo5ZFThrm8OTh5qNyerW",
	"n1h3wYXKOce36YqdosWXHYnXowMzIACACuoxaLvAsa2WDth6pcX9zfMZQTqnUGQO+84o/oQrPlGR7++x",
	"M+6AJnXWrqoxfZfbezFNME5YgjFZlj208pHonFQ9Y8VnGePBXBbM1S3fCv3xNt5ZqAqypYfxKns9Jxij",
	"4aVkB42esSo2+y5fUXUpAx9EaYGZdc3pj7NyX6P1GzqbMn7/mHXaJTY3ak9qzGtmaOiV2qV2L1wHrSq2",
	"3Cx5tjilUrYN9cHSMa2qIrXn0KUqQjsL2H8JP05w7x8ixy9gP/9rFQULSxj8PTCzLgsl128A1ikF1ulb",
	"xa7yTuH7rQfnLQqWY//h78hbE711IBhNeoKxSWgezTX9KTsTGv5UbpTkf62KKDIzUCYAf2dRexo0X3JT",
	"4E2XCSXEWPQO0uv9XgjIV7GOvjcxI0NNOUOLPC82CLn3YVKExalXp0YjPG5z7N0arkPoveRzgsMA1M6Y",
	"6la166Xbe9v/nE3Pp7GA8WbD4jmwC9Q0jxCmm4gAyWXAdggI0AuaxNnC5tCpkGSNjHw/MOM05d6IVgvU",
	"sCX2WBaFM5i2ALTNUmwCcW2gJIZGHYy5LDjI6R0BdhD7IARycku+2VxJN0139AnXFDNl4SpuGGUxcFgw",
	"I1Nx8XIZUVFJwkBrP0hUpSntUUSq49iL9jI5ERtavlKb4HS4syFu6aScEF1EWYdPFUi+1+ofqMGe0le5",
	"ipIbm92D4vKNpjHxS42Jj4LD47FqlXGPcXOQSOkSOkhtRxAyaYZFY1fORF/XftgDLlKT6TSRrqZ/STTS",
	"hyHma8aNa+MJMMSJdkm7JSSnkK/A5B3BfglgJpv0uTHu3T7G6uNLOkRx815cF1OiilFL2/KPh9Kq67fk",
	"NJ4RysS6D8RuzociqPa1rHFR3nsmWKcrE7gv5jAAUwZvcFUtOm0tqlhPuRzm9QhIyXWNJXmcZzYiIEpq",
	"OuRGL9RSgpvnTu/Izb5l6/B5ilmDcyZc46JSEIlTLRL6fn7QNASQpLz4bbR+7KpHR0stidi/USB2UZCO",
	"ZGzzdi5n1F7kwy+rlKh8QsY4tWf88LpL0Z1JJGWhwq8HenOSNsQKNZ6NngkcaWCUlhelbf7PgBouCay+",
	"EdVnOWee1lPA663z5BtdI40n31+3MdE10Xs5YC2MKZIWP9XiaGhUin0ufhCQHGlTWl/SNRFXu+oglxtO",
	"4Gam1T+m28ezR2YM5x0wI7J1Z+ogkiP/eSFRKh86Iq/8l+yQ/YM/7UbeVpnXF/jj2vRzYKvmQpku2OZT",
	"COIL8PoniDuz24jCgY2nWD3AkI2pSV7N6xcVofEHxGlcS/7LCThfvbhin92019Ce0zXj5hp3Q7Yzpt2P",
	"nWSnTYcdsXfc2z1Rm/GqIxvkNrvi1/4OOxLeith3V9vTKDht1Znquf7VTJJq5+3VlPlVaJpcKzmDKSbg",
	"EEBxQ7Sg1SxcvQp9l71Vjig9LTXQcCndZKgvKhg4DWo4zxXqG6gLaJqi1Jx3PXiG8okMGCYSlBcdrcwW",
	"JcRC032MLY7PkkhJhzy2kOU0G/xZ8i6jYHjEUgdzLpRKllOF1qbj0oUPyh+UDT6cmkOGH/5bc+7lNwXN",
	"+RDC4VdX1VFTOediRqcPSHXThWEUKMV7c8SmT51hh+pcyGiCu+L0AuXOaXNDO9xMlA17Z4nuwdgDRdmq",
	"5ol/z541Gmu9jo0Q7cTS5yjJfbYK6b19RW1Izw1J4xMIdkbSGQnSIog5tF+FdBcFqaoaRdJP2g/7sbEf",
	"B2Vumu3TEyeuBlZFFzSkT0mNPWZVpRKyrn1Oic2+/2Xs58shd2tPq0psmyRLbdOd9WKKqc76F4lFDtq0",
	"NdDUHYQqYRccgyo3h11Z+aiYPuU0DsXwMDjNU75Lbqgiu1gVLfphrNjmBO219v8HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
