package usecase_errors

import "errors"

var (
	ErrTwoFactorRequired       = errors.New("two-factor authentication is required for this account")
	ErrUserAlreadyExists       = errors.New("user with this username already exists")
	ErrInvalidCredentials      = errors.New("invalid username or password")
	ErrUserNotFound            = errors.New("user not found")
	ErrCannotModerateSelf      = errors.New("cannot moderate yourself")
	ErrBlockReasonRequired     = errors.New("block reason is required")
	ErrUserAlreadyBlocked      = errors.New("user is already blocked")
	ErrUserNotBlocked          = errors.New("user is not blocked")
	ErrInvalidSession          = errors.New("invalid or expired session")
	ErrUserBlocked             = errors.New("user is blocked")
	ErrUsernameAlreadyExists   = errors.New("username already exists")
	ErrCountryNotFound         = errors.New("country not found")
	ErrCitiesNotFound          = errors.New("cities not found")
	ErrCityNotFound            = errors.New("cities not found")
	ErrPlaceNotFound           = errors.New("place not found")
	ErrPlacesNotFound          = errors.New("places not found")
	ErrReviewNotFound          = errors.New("review not found")
	ErrReviewAlreadyExists     = errors.New("user has already reviewed this place")
	ErrReviewAlreadyModerated  = errors.New("review has already been moderated")
	ErrReviewsNotFound         = errors.New("reviews not found")
	ErrNotAuthorized           = errors.New("not authorized to perform this action")
	ErrTripNotFound            = errors.New("trip not found")
	ErrStaticPageNotFound      = errors.New("static page not found")
	ErrSlugAlreadyExists       = errors.New("slug not found")
	ErrInvalidVerificationCode = errors.New("invalid or expired verification code")
	ErrInvalidTwoFactorCode    = errors.New("invalid two-factor authentication code")
	ErrEmailNotVerified        = errors.New("email not verified, please verify your account")
	ErrTooManyAttempts         = errors.New("too many attempts, please try again later")
	ErrInvalidReportType       = errors.New("invalid")
	ErrInvalidImageType        = errors.New("invalid image type, allowed: jpeg, png, webp")
	ErrForbidden               = errors.New("forbidden")
)
