package domain

import "errors"

var (
	ErrEmptyCityDistrictName          = errors.New("city district name cannot be empty")
	ErrCityDistrictNameTooLong        = errors.New("city district name exceeds maximum length of 255 characters")
	ErrEmptyCityDistrictDescription   = errors.New("city district description cannot be empty")
	ErrCityDistrictDescriptionTooLong = errors.New("city district description exceeds maximum length of 1024 characters")
	ErrInvalidCityID                  = errors.New("city ID is required and must be non-zero")

	ErrInvalidLatitude  = errors.New("latitude must be between -90 and 90")
	ErrInvalidLongitude = errors.New("longitude must be between -180 and 180")

	ErrEmptyUsername      = errors.New("username cannot be empty")
	ErrUsernameTooLong    = errors.New("username exceeds maximum length of 100 characters")
	ErrEmptyEmail         = errors.New("email cannot be empty")
	ErrEmailTooLong       = errors.New("email exceeds maximum length of 255 characters")
	ErrInvalidEmailFormat = errors.New("invalid email format")
	ErrEmptyPasswordHash  = errors.New("password hash cannot be empty")
	ErrEmptyPassword      = errors.New("password cannot be empty")
	ErrPasswordTooShort   = errors.New("password must be at least 6 characters")
	ErrPasswordTooLong    = errors.New("password exceeds maximum length of 72 characters")

	ErrEmptyCityName          = errors.New("city name cannot be empty")
	ErrCityNameTooLong        = errors.New("city name exceeds maximum length of 255 characters")
	ErrCityDescriptionTooLong = errors.New("city description exceeds maximum length of 2000 characters")
	ErrEmptyCityDescription   = errors.New("city description cannot be empty")
	ErrCityTimezoneTooLong    = errors.New("timezone string exceeds maximum length of 50 characters")
	ErrCityTravelTipsTooLong  = errors.New("travel tips exceed maximum length of 2000 characters")
	ErrInvalidCountryID       = errors.New("country ID is required and must be non-zero")
	ErrCityNegativePopulation = errors.New("city population cannot be negative")

	ErrEmptyCountryName        = errors.New("country name cannot be empty")
	ErrCountryNameTooLong      = errors.New("country name exceeds maximum length of 255 characters")
	ErrCurrencyTooLong         = errors.New("currency code exceeds maximum length of 3 characters")
	ErrLanguageTooLong         = errors.New("language name exceeds maximum length of 100 characters")
	ErrPhoneCodeTooLong        = errors.New("phone code exceeds maximum length of 10 characters")
	ErrNegativeArea            = errors.New("area cannot be negative")
	ErrDescriptionTooLong      = errors.New("description exceeds maximum length of 2000 characters")
	ErrVisaRequirementsTooLong = errors.New("visa requirements exceed maximum length of 200 characters")

	ErrEmptyHolidayName   = errors.New("holiday name cannot be empty")
	ErrHolidayNameTooLong = errors.New("holiday name exceeds maximum length of 255 characters")
	ErrInvalidDate        = errors.New("date cannot be zero")

	ErrEmptyPlaceName           = errors.New("place name cannot be empty")
	ErrPlaceNameTooLong         = errors.New("place name exceeds maximum length of 255 characters")
	ErrEmptyPlaceCategory       = errors.New("place category cannot be empty")
	ErrPlaceCategoryTooLong     = errors.New("place category exceeds maximum length of 50 characters")
	ErrPlaceDescriptionTooLong  = errors.New("place description exceeds maximum length of 2000 characters")
	ErrPlaceAddressTooLong      = errors.New("place address exceeds maximum length of 500 characters")
	ErrPlaceOpeningHoursTooLong = errors.New("opening hours exceed maximum length of 500 characters")
	ErrPlacePriceInfoTooLong    = errors.New("price info exceeds maximum length of 500 characters")
	ErrNegativeVisitDuration    = errors.New("visit duration cannot be negative")

	ErrInvalidRating     = errors.New("rating must be between 1 and 5")
	ErrEmptyComment      = errors.New("comment cannot be empty")
	ErrCommentTooLong    = errors.New("comment exceeds maximum length of 2000 characters")
	ErrVisitDateInFuture = errors.New("visit date cannot be in the future")
	ErrInvalidUserID     = errors.New("user ID is required and must be non-zero")
	ErrInvalidPlaceID    = errors.New("place ID is required and must be non-zero")

	ErrEmptyTripTitle         = errors.New("trip title cannot be empty")
	ErrTripTitleTooLong       = errors.New("trip title exceeds maximum length of 255 characters")
	ErrInvalidStartDate       = errors.New("start date is required")
	ErrInvalidEndDate         = errors.New("end date is required")
	ErrEndDateBeforeStartDate = errors.New("end date cannot be before start date")
	ErrNegativeBudget         = errors.New("budget cannot be negative")
	ErrEmptyTripStatus        = errors.New("trip status cannot be empty")
	ErrInvalidTripStatus      = errors.New("invalid trip status")
	ErrTripNotesTooLong       = errors.New("trip notes exceed maximum length of 2000 characters")

	ErrEmptyStaticPageSlug              = errors.New("static page slug cannot be empty")
	ErrStaticPageSlugTooLong            = errors.New("slug exceeds maximum length of 100 characters")
	ErrEmptyStaticPageTitle             = errors.New("static page title cannot be empty")
	ErrStaticPageTitleTooLong           = errors.New("title exceeds maximum length of 255 characters")
	ErrEmptyStaticPageContent           = errors.New("static page content cannot be empty")
	ErrStaticPageContentTooLong         = errors.New("content exceeds maximum length of 10000 characters")
	ErrStaticPageMetaDescriptionTooLong = errors.New("meta description exceeds maximum length of 500 characters")
	ErrStaticPageImageURLTooLong        = errors.New("image URL exceeds maximum length of 500 characters")
	ErrStaticPageImageAltTooLong        = errors.New("image alt text exceeds maximum length of 255 characters")

	ErrEmptyTransportNodeName      = errors.New("transport node name cannot be empty")
	ErrTransportNodeNameTooLong    = errors.New("transport node name exceeds maximum length of 255 characters")
	ErrEmptyTransportNodeType      = errors.New("transport node type cannot be empty")
	ErrTransportNodeTypeTooLong    = errors.New("transport node type exceeds maximum length of 50 characters")
	ErrInvalidTransportNodeType    = errors.New("invalid transport node type")
	ErrTransportNodeAddressTooLong = errors.New("address exceeds maximum length of 500 characters")

	ErrInvalidDayNumber         = errors.New("day number must be positive")
	ErrNegativeDuration         = errors.New("duration cannot be negative")
	ErrTripPlaceNotesTooLong    = errors.New("trip place notes exceed maximum length of 2000 characters")
	ErrEmptyVisitStatus         = errors.New("visit status cannot be empty")
	ErrInvalidVisitStatus       = errors.New("invalid visit status")
	ErrNegativeActualCost       = errors.New("actual cost cannot be negative")
	ErrInvalidTripID            = errors.New("trip ID is required and must be non-zero")
	ErrPlaceContactPhoneTooLong = errors.New("contact phone exceeds maximum length of 50 characters")
	ErrPlaceWebsiteTooLong      = errors.New("website URL exceeds maximum length of 255 characters")

	ErrNegativeGDP       = errors.New("GDP cannot be negative")
	ErrBestSeasonTooLong = errors.New("best season exceeds maximum length of 50 characters")
	ErrReligionTooLong   = errors.New("religion exceeds maximum length of 100 characters")

	ErrInvalidHolidayDate = errors.New("holiday date is required")

	ErrPhoneTooLong            = errors.New("phone number exceeds maximum length of 50 characters")
	ErrCountryResidenceTooLong = errors.New("country of residence exceeds maximum length of 100 characters")
	ErrInvalidPhoneFormat      = errors.New("invalid phone number format")
	ErrInvalidURLFormat        = errors.New("invalid URL format")

	ErrInvalidPhone    = errors.New("invalid format of phone")
	ErrInvalidWebsite  = errors.New("invalid format of website")
	ErrInvalidUserRole = errors.New("invalid user role")

	ErrStaticPageNotFound = errors.New("static page not found")
	ErrFileNotFound       = errors.New("file not found")
	ErrTripNotFound       = errors.New("trip not found")
	ErrPlaceNotFound      = errors.New("place not found")
	ErrReviewNotFound     = errors.New("review not found")
)
